Repository gazebosim/gz-rendering, pull requests merged in 2020-10, with the labels that each got.

#141 Add unversioned symlinks for engine plugins
  CMakeLists.txt
  ogre/src/CMakeLists.txt
  ogre2/src/CMakeLists.txt
  optix/src/CMakeLists.txt
Labels: 🏰 citadel

#155 Limit number of shadow casting lights in ogre2
  ogre2/src/Ogre2RenderTarget.cc
Labels: 📜 blueprint

#157 Prepare for 2.5.1 release
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#159 Update particles tutorial image
  tutorials/20_particles_tutorial.md
  tutorials/img/particles.gif
  tutorials/img/particles.png
Labels: 🔮 dome

#162 Nate/2 to 3 oct 2020
  CMakeLists.txt
  Changelog.md
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderTarget.cc
Labels: 🏰 citadel

#154 Add Custom Render Plugin Example
  examples/hello_world_plugin/CMakeLists.txt
  examples/hello_world_plugin/HelloWorldPlugin.cc
  examples/hello_world_plugin/README.md
  include/ignition/rendering/RenderingIface.hh
  src/base/BaseRenderEngine.cc
  tutorials.md.in
  tutorials/03_rendering_plugins.md
Labels: 🏰 citadel

#161 Add Rendering Plugin Tutorial
  tutorials/03_rendering_plugins.md
Labels: documentation, 🏰 citadel

#164 Prepare 3.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#165 Improve fork experience
  .github/workflows/ci.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel

#169 Fix crash due to NaN pose values
  include/ignition/rendering/base/BaseNode.hh
  include/ignition/rendering/base/BaseVisual.hh
  src/Node_TEST.cc
Labels: 🏰 citadel
