Repository gazebosim/gz-rendering, pull requests merged in 2020-08, with the labels that each got.

#119 2 ➡️ 3
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  Changelog.md
  README.md
  ogre/src/OgreThermalCamera.cc
  ogre2/src/Ogre2ThermalCamera.cc
  test/integration/depth_camera.cc
Labels: 🏰 citadel

#116 Ogre2 Implementation for Lidar Visual
  Changelog.md
  examples/lidar_visual/GlutWindow.cc
  examples/lidar_visual/Main.cc
  include/ignition/rendering/base/BaseLidarVisual.hh
  ogre/src/OgreLidarVisual.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2LidarVisual.hh
  ogre2/src/Ogre2LidarVisual.cc
  test/integration/lidar_visual.cc
Labels: enhancement, 🔮 dome

#120 3 ➡️ 4
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  Changelog.md
  README.md
  ogre/src/OgreGrid.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2Grid.cc
  test/integration/depth_camera.cc
  test/test_config.h.in
Labels: 🔮 dome

#122 Add support for Gaussian noise render pass in Ogre2DepthCamera
  ogre2/include/ignition/rendering/ogre2/Ogre2DepthCamera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GaussianNoisePass.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/media/materials/programs/depth_camera_final_fs.glsl
  ogre2/src/media/materials/programs/depth_camera_final_vs.glsl
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gaussian_noise_depth_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  ogre2/src/media/materials/scripts/gaussian_noise.material
  test/integration/render_pass.cc
Labels: 📜 blueprint

#123 2.5.0 release prep
  CMakeLists.txt
  Changelog.md
Labels: 📜 blueprint

#126 Particles tutorial
  examples/particles_demo/Main.cc
  tutorials.md.in
  tutorials/20_particles_tutorial.md
  tutorials/img/particles.png
Labels: documentation, 🔮 dome

#124 Add LidarVisual point colors for Ogre1
  include/ignition/rendering/LidarVisual.hh
  include/ignition/rendering/base/BaseLidarVisual.hh
  ogre/include/ignition/rendering/ogre/OgreLidarVisual.hh
  ogre/src/OgreLidarVisual.cc
  ogre/src/media/materials/programs/point_fs.glsl
  ogre/src/media/materials/programs/point_vs.glsl
  ogre/src/media/materials/scripts/point_cloud_point.material
Labels: 🔮 dome

#132 minor change in LidarVisual for the case when sensor data is more than sensor range
  ogre/src/OgreLidarVisual.cc
  ogre2/src/Ogre2LidarVisual.cc
Labels: 🔮 dome

#125 Removed repeated installation instructions
  README.md
  tutorials/02_install.md
Labels: documentation, 🔮 dome
