Repository gazebosim/gz-rendering, pull requests merged in 2020-07, with the labels that each got.

#107 Particle emitter - part1
  include/ignition/rendering/ParticleEmitter.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseParticleEmitter.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreParticleEmitter.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/src/OgreParticleEmitter.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/src/Ogre2ParticleEmitter.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/base/BaseScene.cc
Labels: enhancement, 🔮 dome

#103 Added LidarVisual implementation for Ogre1, empty classes for Ogre2
  Changelog.md
  examples/lidar_visual/CMakeLists.txt
  examples/lidar_visual/GlutWindow.cc
  examples/lidar_visual/GlutWindow.hh
  examples/lidar_visual/Main.cc
  examples/lidar_visual/README.md
  examples/lidar_visual/example_config.hh.in
  include/ignition/rendering/LidarVisual.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseLidarVisual.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreLidarVisual.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreLidarVisual.cc
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2LidarVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2LidarVisual.cc
  ogre2/src/Ogre2Scene.cc
  src/LidarVisual.cc
  src/LidarVisual_TEST.cc
  src/base/BaseScene.cc
  test/integration/CMakeLists.txt
  test/integration/lidar_visual.cc
Labels: enhancement, ogre1.x, 🔮 dome

#104 Add environment variable to locate plugins
  ogre/src/OgreRenderEngine.cc
  ogre2/src/Ogre2RenderEngine.cc
  src/RenderEngineManager.cc
Labels: enhancement, 🔮 dome

#113 Particle emitter - part2
  include/ignition/rendering/ParticleEmitter.hh
  include/ignition/rendering/base/BaseParticleEmitter.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Scene.cc
  src/ParticleEmitter.cc
  src/ParticleEmitter_TEST.cc
  src/base/BaseScene.cc
Labels: 🔮 dome

#114 Add types for lidar visual
  Changelog.md
  examples/lidar_visual/GlutWindow.cc
  examples/lidar_visual/GlutWindow.hh
  examples/lidar_visual/Main.cc
  include/ignition/rendering/LidarVisual.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseLidarVisual.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/src/OgreLidarVisual.cc
  ogre/src/OgreRenderEngine.cc
  ogre2/src/Ogre2RenderEngine.cc
  src/LidarVisual_TEST.cc
  src/RenderEngineManager.cc
  src/base/BaseScene.cc
  test/integration/lidar_visual.cc
Labels: 🔮 dome

#115 Fix tests on actions
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  test/integration/depth_camera.cc
Labels: tests, 📜 blueprint
