Repository gazebosim/gz-rendering, pull requests merged in 2020-05, with the labels that each got.

#79 [ign-rendering2] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
Labels: 📜 blueprint

#81 [master] Workflow updates
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
Labels: 🔮 dome

#80 [ign-rendering3] Workflow updates
  .github/CODEOWNERS
  .github/workflows/ci-bionic.yml
  .github/workflows/pr-collection-labeler.yml
  .github/workflows/triage.yml
  README.md
Labels: 🏰 citadel

#87 Add ogre2 AxisVisual and ArrowVisual
  Changelog.md
  examples/simple_demo/GlutWindow.cc
  examples/simple_demo/Main.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2ArrowVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2AxisVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/src/Ogre2ArrowVisual.cc
  ogre2/src/Ogre2AxisVisual.cc
  ogre2/src/Ogre2Scene.cc
  src/ArrowVisual_TEST.cc
  src/AxisVisual_TEST.cc
  tutorials/18_simple_demo_tutorial.md
Labels: 🔮 dome

#88 Scale BaseAxis properly
  Changelog.md
  include/ignition/rendering/base/BaseAxisVisual.hh
Labels: 🔮 dome
