Repository gazebosim/gz-rendering, pull requests merged in 2020-11, with the labels that each got.

#168 Add ogre2 skybox support
  Changelog.md
  examples/ogre2_demo/GlutWindow.cc
  examples/ogre2_demo/Main.cc
  examples/ogre2_demo/media/skybox_lowres.dds
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2Scene.cc
  ogre2/src/media/materials/programs/skybox_fs.glsl
  ogre2/src/media/materials/programs/skybox_vs.glsl
  ogre2/src/media/materials/scripts/skybox.material
  ogre2/src/media/materials/textures/skybox.dds
  src/Camera_TEST.cc
  src/RenderTarget_TEST.cc
  src/Scene_TEST.cc
  src/base/BaseScene.cc
  test/integration/CMakeLists.txt
  test/integration/sky.cc
Labels: 🏢 edifice

#173 Resolve updated codecheck issues
  ogre/src/OgreRenderEngine.cc
  ogre2/src/Ogre2RenderEngine.cc
Labels: 📜 blueprint

#174 👩‍🌾 Make flaky VisualAt test more verbose
  test/integration/camera.cc
Labels: tests, 🏰 citadel

#172 ⬆️ 4.1.0
  CMakeLists.txt
  Changelog.md
  Migration.md
Labels: 🔮 dome

#176 2 to 3
  ogre/src/OgreRenderEngine.cc
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🏰 citadel

#177 3 to 4
  include/ignition/rendering/base/BaseNode.hh
  include/ignition/rendering/base/BaseVisual.hh
  ogre/src/OgreRenderEngine.cc
  ogre2/src/Ogre2RenderEngine.cc
  src/Node_TEST.cc
  test/integration/camera.cc
Labels: 🔮 dome
