Repository gazebosim/gz-rendering, pull requests merged in 2020-12, with the labels that each got.

#183 Remove some windows warnings
  include/ignition/rendering/MeshDescriptor.hh
Labels: enhancement, 🔮 dome

#186 Fix transparency issue for textures without alpha channel
  ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh
  ogre2/src/Ogre2Material.cc
Labels: 🔮 dome

#182 Add support for lightmaps in ogre2
  CMakeLists.txt
  include/ignition/rendering/Material.hh
  include/ignition/rendering/base/BaseMaterial.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2MeshFactory.cc
  src/Material_TEST.cc
Labels: 🏢 edifice

#190 Extending simple_demo to include render order
  examples/simple_demo/Main.cc
  include/ignition/rendering/MeshDescriptor.hh
  ogre2/src/Ogre2Material.cc
  tutorials/21_render_order.md
  tutorials/img/render_order_bad.png
  tutorials/img/render_order_good.png
Labels: 🔮 dome
