Repository gazebosim/gz-rendering, pull requests merged in 2020-09, with the labels that each got.

#133 Adding option for visibility
  ogre/include/ignition/rendering/ogre/OgreLidarVisual.hh
  ogre/src/OgreLidarVisual.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2LidarVisual.hh
  ogre2/src/Ogre2LidarVisual.cc
Labels: 🔮 dome

#130 Merge ign-rendering2 to ign-rendering3
  Changelog.md
  ogre2/include/ignition/rendering/ogre2/Ogre2DepthCamera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GaussianNoisePass.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/media/materials/programs/depth_camera_final_fs.glsl
  ogre2/src/media/materials/programs/depth_camera_final_vs.glsl
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gaussian_noise_depth_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  ogre2/src/media/materials/scripts/gaussian_noise.material
  test/integration/depth_camera.cc
  test/integration/render_pass.cc
Labels: 🏰 citadel

#137 Pimpl'ize ogre2 classes
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2GaussianNoisePass.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Light.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2MeshFactory.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderPass.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Visual.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2GaussianNoisePass.cc
  ogre2/src/Ogre2Light.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2MeshFactory.cc
  ogre2/src/Ogre2RenderPass.cc
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2Visual.cc
Labels: beta, ogre2.x, 🔮 dome

#135 Replace common::Time with std::chrono
  CMakeLists.txt
  Migration.md
  examples/gazebo_scene_viewer/SceneManager.cc
  examples/gazebo_scene_viewer/SceneManagerPrivate.hh
  examples/ogre2_demo/GlutWindow.cc
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseScene.hh
  src/Scene_TEST.cc
  src/base/BaseScene.cc
  test/integration/gpu_rays.cc
Labels: beta, enhancement, needs upstream release, 🔮 dome

#143 Updates to tutorials
  tutorials/11_gazebo_scene_viewer_tutorial.md
  tutorials/12_mesh_viewer_tutorial.md
  tutorials/13_custom_scene_viewer.md
  tutorials/14_camera_tracking_tutorial.md
  tutorials/15_custom_shaders_tutorial.md
  tutorials/17_render_pass_tutorial.md
  tutorials/18_simple_demo_tutorial.md
  tutorials/19_text_geom_tutorial.md
  tutorials/20_particles_tutorial.md
Labels: documentation, 🔮 dome

#144 Update actor animation tutorial
  examples/actor_animation/GlutWindow.cc
  examples/actor_animation/Main.cc
  tutorials/10_actor_animation_tutorial.md
  tutorials/img/actor_animation.png
Labels: 🔮 dome

#138 Backport ogre2 depth camera fix
  ogre2/src/Ogre2DepthCamera.cc
Labels: 📜 blueprint

#145 Update camera tracking tutorial
  examples/camera_tracking/GlutWindow.cc
  tutorials/14_camera_tracking_tutorial.md
Labels: 🔮 dome

#150 Update simple demo tutorial
  tutorials/img/simple_demo.gif
Labels: 🔮 dome

#147 Update gazebo scene viewer tutorial
  examples/gazebo_scene_viewer/CameraWindow.cc
  examples/gazebo_scene_viewer/GazeboDemo.cc
  examples/gazebo_scene_viewer/GazeboWorldDemo.cc
  examples/gazebo_scene_viewer/SceneManager.cc
  tutorials/11_gazebo_scene_viewer_tutorial.md
  tutorials/img/gazebo_scene_viewer.gif
  tutorials/img/gazebo_scene_viewer2_demo.gif
Labels: 🔮 dome

#149 Update render pass tutorial
  tutorials/17_render_pass_tutorial.md
Labels: 🔮 dome

#146 Update custom scene viewer tutorial
  tutorials/13_custom_scene_viewer.md
Labels: 🔮 dome

#148 Update custom shaders tutorial
  examples/custom_shaders/CMakeLists.txt
  examples/custom_shaders/custom_shaders.cc
  examples/custom_shaders/example_config.hh.in
  examples/custom_shaders/media/depth_fragment_shader.glsl
  examples/custom_shaders/media/depth_vertex_shader.glsl
  examples/custom_shaders/media/fragment_shader.glsl
  examples/custom_shaders/media/vertex_shader.glsl
  tutorials/15_custom_shaders_tutorial.md
  tutorials/17_render_pass_tutorial.md
  tutorials/img/custom_shaders_depth.png
Labels: 🔮 dome

#151 Update installation tutorial
  tutorials/02_install.md
Labels: 🔮 dome

#152 Prepare for 4.0.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#153 Fire breathing duck
  examples/particles_demo/Main.cc
  tutorials/img/particles.png
Labels: 🔮 dome
