Repository gazebosim/gz-rendering, pull requests merged in 2021-08, with the labels that each got.

#371 Prevent default-constructed variants from holding a type
  Migration.md
  include/ignition/rendering/Node.hh
  src/Visual_TEST.cc
Labels: 🏯 fortress

#325 Changed calculation for range clipping
  Migration.md
  ogre2/src/media/materials/programs/depth_camera_final_fs.glsl
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
Labels: 🏯 fortress

#365 Use clipping distance for minimum LIDAR distance
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2IgnHlmsCustomizations.cc
  ogre2/src/Ogre2IgnHlmsCustomizations.hh
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/media/Hlms/Ignition/IgnCustomStructs_piece_all.any
  ogre2/src/media/Hlms/Ignition/Ign_piece_vs.any
  ogre2/src/media/Hlms/Pbs/GLSL/VertexShader_vs.glsl
  ogre2/src/media/materials/programs/plain_color_vs.glsl
  ogre2/src/media/materials/scripts/gpu_rays.material
  ogre2/src/media/materials/scripts/picker.material
  ogre2/src/media/materials/scripts/thermal.material
Labels: 🏯 fortress

#377 Support OpenGL < 4.2 in PBS shader
  ogre2/src/media/Hlms/Pbs/GLSL/BRDFs_piece_ps.glsl
Labels: 🏢 edifice

#382 3 ➡️ 4
  include/ignition/rendering/RayQuery.hh
  include/ignition/rendering/Utils.hh
  src/Utils.cc
  src/Utils_TEST.cc
Labels: 🔮 dome

#366 Joint visual
  examples/visualization_demo/Main.cc
  include/ignition/rendering/ArrowVisual.hh
  include/ignition/rendering/AxisVisual.hh
  include/ignition/rendering/JointVisual.hh
  include/ignition/rendering/Node.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseArrowVisual.hh
  include/ignition/rendering/base/BaseAxisVisual.hh
  include/ignition/rendering/base/BaseJointVisual.hh
  include/ignition/rendering/base/BaseNode.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreJointVisual.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreJointVisual.cc
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2JointVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2JointVisual.cc
  ogre2/src/Ogre2Scene.cc
  src/ArrowVisual_TEST.cc
  src/AxisVisual_TEST.cc
  src/JointVisual_TEST.cc
  src/base/BaseScene.cc
Labels: 🏯 fortress

#385 👩‍🌾 Remove bitbucket-pipelines.yml
  bitbucket-pipelines.yml
Labels: 🏰 citadel

#376 Set OGRE minimal version to 1.8. Warn on versions not supported (ign-rendering3)
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, needs upstream release

#387 Fix JointVisual axis head visibility
  include/ignition/rendering/base/BaseJointVisual.hh
Labels: 🏯 fortress

#389 Improved doxygen
  .github/workflows/ci.yml
  include/ignition/rendering/Camera.hh
  include/ignition/rendering/GaussianNoisePass.hh
  include/ignition/rendering/Geometry.hh
  include/ignition/rendering/GpuRays.hh
  include/ignition/rendering/Light.hh
  include/ignition/rendering/Marker.hh
  include/ignition/rendering/Material.hh
  include/ignition/rendering/Mesh.hh
  include/ignition/rendering/RayQuery.hh
  include/ignition/rendering/RenderEngine.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/Storage.hh
  include/ignition/rendering/Text.hh
  include/ignition/rendering/ThermalCamera.hh
  include/ignition/rendering/TransformController.hh
  include/ignition/rendering/TransformType.hh
  include/ignition/rendering/Utils.hh
  include/ignition/rendering/Visual.hh
  include/ignition/rendering/base/BaseGeometry.hh
  include/ignition/rendering/base/BaseGizmoVisual.hh
  include/ignition/rendering/base/BaseLight.hh
  include/ignition/rendering/base/BaseMaterial.hh
  include/ignition/rendering/base/BaseMesh.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreCamera.hh
  ogre/include/ignition/rendering/ogre/OgreConversions.hh
  ogre/include/ignition/rendering/ogre/OgreMaterial.hh
  ogre/include/ignition/rendering/ogre/OgreRTShaderSystem.hh
  ogre/include/ignition/rendering/ogre/OgreRenderEngine.hh
  ogre/include/ignition/rendering/ogre/OgreSelectionBuffer.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Conversions.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Node.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh
  optix/include/ignition/rendering/optix/OptixCamera.hh
  optix/include/ignition/rendering/optix/OptixMaterial.hh
Labels: 🏰 citadel

#391 Output warning message if a mesh with zero submeshes is created
  ogre/src/OgreMeshFactory.cc
  ogre2/src/Ogre2MeshFactory.cc
Labels: 🔮 dome
