Repository gazebosim/gz-rendering, pull requests merged in 2021-06, with the labels that each got.

#333 Fix floating point precision bug handling alpha channel (#332)
  ogre2/src/media/materials/programs/depth_camera_final_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  test/integration/depth_camera.cc
Labels: 🏢 edifice

#338 Fix new [] / delete mismatch
  src/Image.cc
Labels: 🏢 edifice

#337 Fix heap overflow when reading
  ogre2/src/Ogre2SelectionBuffer.cc
Labels: 🏢 edifice

#313 Fix FSAA in UI and lower VRAM consumption
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTargetMaterial.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2RenderTargetMaterial.cc
Labels: 🏢 edifice

#340 Backport memory fixes found by ASAN
  ogre2/src/Ogre2SelectionBuffer.cc
  src/Image.cc
Labels: 🏰 citadel

#342 Fix ogre2 render pass high GPU usage
  ogre2/src/Ogre2RenderTarget.cc
Labels: 🏰 citadel

#343 Fix custom shaders uniforms ign-rendering package version number
  examples/custom_shaders_uniforms/CMakeLists.txt
Labels: 🏢 edifice

#326 Inertia visual
  examples/visualization_demo/CMakeLists.txt
  examples/visualization_demo/GlutWindow.cc
  examples/visualization_demo/GlutWindow.hh
  examples/visualization_demo/Main.cc
  include/ignition/rendering/InertiaVisual.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseInertiaVisual.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreInertiaVisual.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreInertiaVisual.cc
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2InertiaVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2DynamicRenderable.cc
  ogre2/src/Ogre2InertiaVisual.cc
  ogre2/src/Ogre2Node.cc
  ogre2/src/Ogre2Scene.cc
  src/InertiaVisual_TEST.cc
  src/base/BaseScene.cc
Labels: 🏯 fortress

#344 Relax Gaussian noise test tolerance to fix flaky test
  src/GaussianNoisePass_TEST.cc
Labels: 🏰 citadel

#346 Update light map tutorial
  tutorials/04_lightmap.md
  tutorials/img/lightmap_bake.jpg
  tutorials/img/lightmap_depot_saved.jpg
  tutorials/img/lightmap_material_connection.jpg
  tutorials/img/lightmap_rendered.png
Labels: 🏢 edifice

#347 3 -> 4
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/media/materials/programs/depth_camera_final_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  src/GaussianNoisePass_TEST.cc
  src/Image.cc
  test/integration/depth_camera.cc
Labels: 🔮 dome

#348 🎈 4.8.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#349 4 -> 5
  Changelog.md
  ogre2/src/Ogre2RenderTarget.cc
  src/GaussianNoisePass_TEST.cc
Labels: 🏢 edifice

#350 5 -> 6 (main)
  Changelog.md
  examples/custom_shaders_uniforms/CMakeLists.txt
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTargetMaterial.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2RenderTargetMaterial.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/media/materials/programs/depth_camera_final_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  src/GaussianNoisePass_TEST.cc
  src/Image.cc
  test/integration/depth_camera.cc
  tutorials/04_lightmap.md
  tutorials/img/lightmap_bake.jpg
  tutorials/img/lightmap_depot_saved.jpg
  tutorials/img/lightmap_material_connection.jpg
  tutorials/img/lightmap_rendered.png
Labels: 🏯 fortress

#351 🎈 5.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#345 Center of mass visual
  examples/visualization_demo/Main.cc
  include/ignition/rendering/COMVisual.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseCOMVisual.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreCOMVisual.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreCOMVisual.cc
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2COMVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2COMVisual.cc
  ogre2/src/Ogre2Scene.cc
  src/COMVisual_TEST.cc
  src/base/BaseScene.cc
  src/base/CMakeLists.txt
  src/base/media/CMakeLists.txt
  src/base/media/materials/CMakeLists.txt
  src/base/media/materials/textures/CMakeLists.txt
  src/base/media/materials/textures/com.png
Labels: 🏯 fortress
