Repository gazebosim/gz-rendering, pull requests merged in 2021-07, with the labels that each got.

#361 Fixing camera projection type test
  include/ignition/rendering/base/BaseCamera.hh
Labels: 🏯 fortress

#358 UserData methods moved from Visual to Node
  include/ignition/rendering/Node.hh
  include/ignition/rendering/Visual.hh
  include/ignition/rendering/base/BaseNode.hh
  include/ignition/rendering/base/BaseVisual.hh
Labels: 🏯 fortress

#364 More nullptr checking on Node classes
  ogre/src/OgreNode.cc
  ogre2/src/Ogre2Node.cc
Labels: 🏢 edifice

#353 Replace renderOneFrame for per-workspace update calls
  Changelog.md
  Migration.md
  include/ignition/rendering/Camera.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseCamera.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/Ogre2ThermalCamera.cc
  src/base/BaseScene.cc
Labels: 🏯 fortress

#367 Temporarily set number of camera pass count per flush to 0 in ogre2 to prevent downstream build failures
  include/ignition/rendering/Scene.hh
  ogre2/src/Ogre2Scene.cc
Labels: 🏯 fortress

#363 Moved ScreenToPlane and ScreenToScene from ign-gui to ign-rendering
  include/ignition/rendering/RayQuery.hh
  include/ignition/rendering/Utils.hh
  src/Utils.cc
  src/Utils_TEST.cc
Labels: 🏰 citadel

#368 Fixed screento functions names
  include/ignition/rendering/Utils.hh
  src/Utils.cc
  src/Utils_TEST.cc
Labels: 🏰 citadel
