Repository gazebosim/gz-rendering, pull requests merged in 2021-11, with the labels that each got.

#481 Fix Utils unit test
  src/Utils_TEST.cc
Labels: 🏯 fortress, 🌱 garden

#468 Update internal texture formats used by gpu lidar
  ogre2/src/Ogre2GpuRays.cc
Labels: 🏯 fortress, 🌱 garden

#484 🎈 5.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#485 Remove unused time var in material scripts
  ogre2/src/media/materials/scripts/depth_camera.material
  ogre2/src/media/materials/scripts/gpu_rays.material
Labels: 🔮 dome

#486 More nullptr checking on visuals and base axis
  include/ignition/rendering/base/BaseAxisVisual.hh
  ogre/src/OgreVisual.cc
  ogre2/src/Ogre2Visual.cc
Labels: bug, 🏯 fortress, 🌱 garden

#489 Fix warnings on Windows
  include/ignition/rendering/base/BaseCamera.hh
  include/ignition/rendering/base/BaseRenderTarget.hh
Labels: Windows

#467 Add a depth camera example
  examples/depth_camera/CMakeLists.txt
  examples/depth_camera/GlutWindow.cc
  examples/depth_camera/GlutWindow.hh
  examples/depth_camera/Main.cc
  examples/depth_camera/example_config.hh.in
  examples/depth_camera/media/duck.dae
  examples/depth_camera/media/duck.png
  tutorials.md.in
  tutorials/23_depth_camera_tutorial.md
  tutorials/img/depth_camera_ogre.png
Labels: 🏯 fortress, 🌱 garden

#492 Use ignition-utils1
  .github/ci/packages.apt
  CMakeLists.txt
  src/CMakeLists.txt
Labels: 🌱 garden
