Repository gazebosim/gz-rendering, pull requests merged in 2021-09, with the labels that each got.

#384 Fix single ray gpu lidar
  ogre2/src/Ogre2GpuRays.cc
  test/integration/gpu_rays.cc
Labels: 🔮 dome

#398 3 ➡️ 4
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  bitbucket-pipelines.yml
  include/ignition/rendering/Camera.hh
  include/ignition/rendering/GaussianNoisePass.hh
  include/ignition/rendering/Geometry.hh
  include/ignition/rendering/GpuRays.hh
  include/ignition/rendering/Light.hh
  include/ignition/rendering/Marker.hh
  include/ignition/rendering/Material.hh
  include/ignition/rendering/Mesh.hh
  include/ignition/rendering/RayQuery.hh
  include/ignition/rendering/RenderEngine.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/Storage.hh
  include/ignition/rendering/Text.hh
  include/ignition/rendering/ThermalCamera.hh
  include/ignition/rendering/TransformController.hh
  include/ignition/rendering/TransformType.hh
  include/ignition/rendering/Utils.hh
  include/ignition/rendering/Visual.hh
  include/ignition/rendering/base/BaseGeometry.hh
  include/ignition/rendering/base/BaseGizmoVisual.hh
  include/ignition/rendering/base/BaseLight.hh
  include/ignition/rendering/base/BaseMaterial.hh
  include/ignition/rendering/base/BaseMesh.hh
  include/ignition/rendering/base/BaseParticleEmitter.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreCamera.hh
  ogre/include/ignition/rendering/ogre/OgreConversions.hh
  ogre/include/ignition/rendering/ogre/OgreMaterial.hh
  ogre/include/ignition/rendering/ogre/OgreMesh.hh
  ogre/include/ignition/rendering/ogre/OgreRTShaderSystem.hh
  ogre/include/ignition/rendering/ogre/OgreRenderEngine.hh
  ogre/include/ignition/rendering/ogre/OgreSelectionBuffer.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Conversions.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Mesh.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Node.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh
  optix/include/ignition/rendering/optix/OptixCamera.hh
  optix/include/ignition/rendering/optix/OptixMaterial.hh
Labels: 🔮 dome, beta

#399 4 ➡️ 5
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  bitbucket-pipelines.yml
  include/ignition/rendering/Camera.hh
  include/ignition/rendering/GaussianNoisePass.hh
  include/ignition/rendering/Geometry.hh
  include/ignition/rendering/GpuRays.hh
  include/ignition/rendering/HeightmapDescriptor.hh
  include/ignition/rendering/Light.hh
  include/ignition/rendering/LightVisual.hh
  include/ignition/rendering/Marker.hh
  include/ignition/rendering/Material.hh
  include/ignition/rendering/Mesh.hh
  include/ignition/rendering/RayQuery.hh
  include/ignition/rendering/RenderEngine.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/Storage.hh
  include/ignition/rendering/Text.hh
  include/ignition/rendering/ThermalCamera.hh
  include/ignition/rendering/TransformController.hh
  include/ignition/rendering/TransformType.hh
  include/ignition/rendering/Utils.hh
  include/ignition/rendering/Visual.hh
  include/ignition/rendering/base/BaseGeometry.hh
  include/ignition/rendering/base/BaseGizmoVisual.hh
  include/ignition/rendering/base/BaseLight.hh
  include/ignition/rendering/base/BaseMaterial.hh
  include/ignition/rendering/base/BaseMesh.hh
  include/ignition/rendering/base/BaseParticleEmitter.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreCamera.hh
  ogre/include/ignition/rendering/ogre/OgreConversions.hh
  ogre/include/ignition/rendering/ogre/OgreMaterial.hh
  ogre/include/ignition/rendering/ogre/OgreMesh.hh
  ogre/include/ignition/rendering/ogre/OgreRTShaderSystem.hh
  ogre/include/ignition/rendering/ogre/OgreRenderEngine.hh
  ogre/include/ignition/rendering/ogre/OgreSelectionBuffer.hh
  ogre/src/OgreMarker.cc
  ogre/src/OgreMeshFactory.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Conversions.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Mesh.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Node.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2MeshFactory.cc
  optix/include/ignition/rendering/optix/OptixCamera.hh
  optix/include/ignition/rendering/optix/OptixMaterial.hh
  src/Utils.cc
  src/Utils_TEST.cc
  test/integration/gpu_rays.cc
Labels: beta, 🏢 edifice

#373 [macOS] add a QML version of simple_demo
  examples/simple_demo_qml/CMakeLists.txt
  examples/simple_demo_qml/IgnitionRenderer.cpp
  examples/simple_demo_qml/IgnitionRenderer.h
  examples/simple_demo_qml/Main.cpp
  examples/simple_demo_qml/Main.qml
  examples/simple_demo_qml/Main.qrc
  examples/simple_demo_qml/ThreadRenderer.cpp
  examples/simple_demo_qml/ThreadRenderer.h
  ogre2/src/Ogre2RenderEngine.cc
Labels: macOS, 🏢 edifice

#405 Disable flaky tests on mac
  test/integration/depth_camera.cc
  test/integration/thermal_camera.cc
Labels: tests, macOS, 🏢 edifice

#396 Check if key exists in gpu lidar's user data
  include/ignition/rendering/Node.hh
  include/ignition/rendering/base/BaseNode.hh
  ogre2/src/Ogre2GpuRays.cc
  src/Visual_TEST.cc
  test/integration/gpu_rays.cc
Labels: beta, 🏯 fortress

#383 Use selection buffer in ray question (ogre2) - part 2
  ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/media/materials/programs/selection_buffer_fs.glsl
  ogre2/src/media/materials/scripts/selection_buffer.material
Labels: 🔮 dome

#404 Update simple_demo_qml coding style
  examples/simple_demo_qml/CMakeLists.txt
  examples/simple_demo_qml/IgnitionRenderer.cc
  examples/simple_demo_qml/IgnitionRenderer.cpp
  examples/simple_demo_qml/IgnitionRenderer.h
  examples/simple_demo_qml/IgnitionRenderer.hh
  examples/simple_demo_qml/Main.cc
  examples/simple_demo_qml/Main.cpp
  examples/simple_demo_qml/Main.qml
  examples/simple_demo_qml/ThreadRenderer.cpp
  examples/simple_demo_qml/ThreadRenderer.h
Labels: 🏢 edifice

#407 Update test config to run ogre 1.x tests in ign-rendering6 on macOS
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2ThermalCamera.cc
  test/test_config.h.in
Labels: beta, 🏯 fortress

#388 Fix particle effect randomness
  ogre2/src/Ogre2ParticleNoiseListener.cc
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
Labels: 🔮 dome

#378 Use selection buffer in ray queries (ogre2)
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/media/materials/programs/selection_buffer_fs.glsl
  ogre2/src/media/materials/scripts/selection_buffer.material
Labels: 🔮 dome

#392 Add SetSize API for LidarVisual
  examples/lidar_visual/Main.cc
  examples/lidar_visual/README.md
  include/ignition/rendering/LidarVisual.hh
  include/ignition/rendering/Marker.hh
  include/ignition/rendering/base/BaseLidarVisual.hh
  include/ignition/rendering/base/BaseMarker.hh
  ogre/src/OgreLidarVisual.cc
  ogre/src/OgreMarker.cc
  ogre/src/media/materials/programs/point_vs.glsl
  ogre/src/media/materials/scripts/point_cloud_point.material
  ogre2/src/Ogre2DynamicRenderable.cc
  ogre2/src/Ogre2LidarVisual.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/media/materials/programs/point_fs.glsl
  ogre2/src/media/materials/programs/point_vs.glsl
  ogre2/src/media/materials/scripts/point_cloud_point.material
  src/LidarVisual_TEST.cc
  src/Marker_TEST.cc
Labels: beta, 🏯 fortress

#406 5 -> 6
  examples/simple_demo_qml/CMakeLists.txt
  examples/simple_demo_qml/IgnitionRenderer.cc
  examples/simple_demo_qml/IgnitionRenderer.hh
  examples/simple_demo_qml/Main.cc
  examples/simple_demo_qml/Main.qml
  examples/simple_demo_qml/Main.qrc
  examples/simple_demo_qml/ThreadRenderer.cpp
  examples/simple_demo_qml/ThreadRenderer.h
  ogre2/src/Ogre2RenderEngine.cc
  test/integration/depth_camera.cc
  test/integration/thermal_camera.cc
Labels: beta, 🏯 fortress

#410 Prepare for 4.9.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#411 Avoid configure warning when checking ogre-1.10
  CMakeLists.txt
Labels: 🏰 citadel

#409 Fix ogre 1.x tests
  ogre/src/OgreGpuRays.cc
  ogre/src/OgreMesh.cc
  ogre/src/OgreNode.cc
  src/Utils_TEST.cc
  test/integration/gpu_rays.cc
Labels: bug, macOS, beta, 🏯 fortress

#329 Segmentation Camera
  examples/segmentation_camera/CMakeLists.txt
  examples/segmentation_camera/GlutWindow.cc
  examples/segmentation_camera/GlutWindow.hh
  examples/segmentation_camera/Main.cc
  examples/segmentation_camera/example_config.hh.in
  examples/segmentation_camera/media/duck.dae
  examples/segmentation_camera/media/duck.png
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/SegmentationCamera.hh
  include/ignition/rendering/base/BaseScene.hh
  include/ignition/rendering/base/BaseSegmentationCamera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SegmentationCamera.hh
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2SegmentationCamera.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.hh
  ogre2/src/Ogre2ThermalCamera.cc
  src/SegmentationCamera_TEST.cc
  src/base/BaseScene.cc
  test/integration/CMakeLists.txt
  test/integration/segmentation_camera.cc
Labels: beta, 🏯 fortress

#417 Prepare for 6.0.0 pre1 release
  Changelog.md
Labels: 🏯 fortress

#416 Address remaining Ogre2 heightmap comments
  examples/heightmap/Main.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Heightmap.hh
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2Scene.cc
Labels: bug, beta, 🏯 fortress

#419 Be consistent in RGB channel notation for ogre2 segmentation camera
  ogre2/src/Ogre2SegmentationCamera.cc
Labels: bug, beta, 🏯 fortress

#418 Minor tweaks to visual cloning
  include/ignition/rendering/Mesh.hh
  include/ignition/rendering/base/BaseMesh.hh
  ogre/src/OgreMeshFactory.cc
  ogre/src/OgreScene.cc
  ogre2/src/Ogre2MeshFactory.cc
  ogre2/src/Ogre2Scene.cc
  src/Mesh_TEST.cc
Labels: beta, 🏯 fortress

#397 Clone visuals and geometries
  include/ignition/rendering/Geometry.hh
  include/ignition/rendering/Mesh.hh
  include/ignition/rendering/Visual.hh
  include/ignition/rendering/base/BaseCapsule.hh
  include/ignition/rendering/base/BaseGeometry.hh
  include/ignition/rendering/base/BaseMesh.hh
  include/ignition/rendering/base/BaseVisual.hh
  ogre/include/ignition/rendering/ogre/OgreCOMVisual.hh
  ogre/include/ignition/rendering/ogre/OgreInertiaVisual.hh
  ogre/include/ignition/rendering/ogre/OgreLightVisual.hh
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2COMVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2InertiaVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2LightVisual.hh
  ogre2/src/Ogre2Scene.cc
  src/Capsule_TEST.cc
  src/Mesh_TEST.cc
  src/Visual_TEST.cc
Labels: beta, 🏯 fortress

#420 add bounding box sensor API stubs
  .github/ci/packages.apt
  CMakeLists.txt
  include/ignition/rendering/BoundingBox.hh
  include/ignition/rendering/BoundingBoxCamera.hh
  include/ignition/rendering/PixelFormat.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseBoundingBoxCamera.hh
  include/ignition/rendering/base/BaseScene.hh
  src/BoundingBox.cc
  src/BoundingBox_TEST.cc
  src/PixelFormat.cc
  src/PixelFormat_TEST.cc
  src/base/BaseScene.cc
Labels: beta, 🏯 fortress

#421 🎈 6.0.0~pre2
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏯 fortress

#413 Fix the spelling of USE_UNOFFICIAL_OGRE_VERSIONS flag
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#423 Merge 3 -> 4
  CMakeLists.txt
  Changelog.md
  test/integration/camera.cc
  test/integration/scene.cc
Labels: 🔮 dome

#426 Update Installation instruction to install ogre 2.2
  tutorials/02_install.md
Labels: documentation, beta, 🏯 fortress

#424 Merge 4 -> 5
  CMakeLists.txt
  Changelog.md
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2ParticleNoiseListener.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/selection_buffer_fs.glsl
  ogre2/src/media/materials/scripts/selection_buffer.material
  test/integration/camera.cc
  test/integration/scene.cc
Labels: 🏢 edifice

#434 Visual cloning: check for null children and recursively delete cloned visuals if failure occurs
  include/ignition/rendering/base/BaseVisual.hh
Labels: beta, 🏯 fortress

#425 Add note about optix in README
  README.md
Labels: 🏯 fortress

#431 Update Heightmap tutorial image
  tutorials/img/heightmaps.png
Labels: documentation, beta, 🏯 fortress

#438 Fix ray query distance calculation
  ogre2/src/Ogre2RayQuery.cc
  src/Utils_TEST.cc
Labels: 🔮 dome

#437 Merge 5 -> 6
  CMakeLists.txt
  Changelog.md
  ogre/src/OgreVisual.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2SelectionBuffer.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2ParticleNoiseListener.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/Ogre2Visual.cc
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/selection_buffer_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  ogre2/src/media/materials/scripts/gpu_rays.material
  ogre2/src/media/materials/scripts/selection_buffer.material
  src/JointVisual_TEST.cc
  src/Utils_TEST.cc
  test/integration/camera.cc
  test/integration/scene.cc
Labels: bug, beta, 🏯 fortress

#440 Fix occasional flickering issue when skybox and directional light shadows are enabled.
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderTarget.cc
Labels: bug, beta, 🏯 fortress

#436 Non desired window opening alongside ignition GUI
  include/ignition/rendering/base/BaseRenderEngine.hh
  ogre2/src/Ogre2RenderEngine.cc
Labels: bug, beta, 🏯 fortress

#443 Hide heightmaps in segmentation camera
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Heightmap.cc
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
Labels: bug, beta, 🏯 fortress

#445 🎈 6.0.0
  CMakeLists.txt
  Changelog.md
  README.md
Labels: beta, 🏯 fortress
