Repository gazebosim/gz-rendering, pull requests merged in 2021-04, with the labels that each got.

#295 Add environment map tutorial
  examples/ogre2_demo/Main.cc
  tutorials.md.in
  tutorials/22_environment_map.md
  tutorials/img/ogre2_sky_envmap.png
  tutorials/img/skybox_gimp_layers.png
Labels: documentation, 🏢 edifice

#282 Silence noisy sky error
  src/base/BaseScene.cc
Labels: 🏢 edifice

#289 Fix gazebo scene viewer build
  examples/gazebo_scene_viewer/CameraWindow.cc
  examples/gazebo_scene_viewer/SceneManager.cc
Labels: 🏢 edifice

#301 Prevent texture spam
  ogre/src/OgreMeshFactory.cc
  ogre2/src/Ogre2MeshFactory.cc
Labels: 🔮 dome

#302 Add light map tutorial
  tutorials.md.in
  tutorials/04_lightmap.md
  tutorials/img/lightmap_depot_render.png
  tutorials/img/lightmap_import.png
  tutorials/img/lightmap_material_shader.png
  tutorials/img/lightmap_new_texture.png
  tutorials/img/lightmap_unwrap.png
Labels: 🏢 edifice, 🏯 fortress

#306 Update spot light visual size
  include/ignition/rendering/base/BaseLightVisual.hh
Labels: 🏢 edifice, 🏯 fortress

#296 Reduce lidar data discretization
  ogre2/src/Ogre2GpuRays.cc
Labels: 🔮 dome

#303 Add shadows to Ogre2DepthCamera without crashing
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2DepthCamera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2Scene.cc
Labels: 🏢 edifice

#310 Merge 5 -> 6
  Changelog.md
  examples/gazebo_scene_viewer/CameraWindow.cc
  examples/gazebo_scene_viewer/SceneManager.cc
  include/ignition/rendering/base/BaseLightVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Capsule.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Conversions.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2DepthCamera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2DynamicRenderable.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2GaussianNoisePass.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2GpuRays.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Grid.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2LidarVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Light.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2LightVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Marker.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2MaterialSwitcher.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderPass.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTargetMaterial.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2ThermalCamera.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2WireBox.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2Conversions.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2DynamicRenderable.cc
  ogre2/src/Ogre2GaussianNoisePass.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2LidarVisual.cc
  ogre2/src/Ogre2Light.cc
  ogre2/src/Ogre2LightVisual.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  ogre2/src/Ogre2Mesh.cc
  ogre2/src/Ogre2MeshFactory.cc
  ogre2/src/Ogre2Node.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2RenderTargetMaterial.cc
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  src/base/BaseScene.cc
  tutorials.md.in
  tutorials/04_lightmap.md
  tutorials/img/lightmap_depot_render.png
  tutorials/img/lightmap_import.png
  tutorials/img/lightmap_material_shader.png
  tutorials/img/lightmap_new_texture.png
  tutorials/img/lightmap_unwrap.png
Labels: 🏯 fortress
