Repository gazebosim/gz-rendering, pull requests merged in 2021-02, with the labels that each got.

#189 Thermal Camera: Visualize objects with a heat signature
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/materials/programs/heat_signature_fs.glsl
  ogre2/src/media/materials/programs/thermal_camera_fs.glsl
  ogre2/src/media/materials/scripts/thermal.material
  test/integration/thermal_camera.cc
  test/media/materials/textures/gray_texture.png
Labels: 🔮 dome

#194 Add laser retro support in Ogre2
  ogre2/include/ignition/rendering/ogre2/Ogre2GpuRays.hh
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_2nd_pass_fs.glsl
  ogre2/src/media/materials/scripts/gpu_rays.material
  test/integration/gpu_rays.cc
Labels: 🏰 citadel

#222 4.3.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#202 Added LightVisual
  Changelog.md
  include/ignition/rendering/LightVisual.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseLightVisual.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreLightVisual.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreLightVisual.cc
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2LightVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2LightVisual.cc
  ogre2/src/Ogre2Scene.cc
  src/LightVisual_TEST.cc
  src/base/BaseScene.cc
Labels: 🏢 edifice

#225 Fix coding style issues
  ogre/include/ignition/rendering/ogre/OgreMaterialSwitcher.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTargetMaterial.hh
  ogre2/src/Ogre2GpuRays.cc
Labels: 🔮 dome

#230 Fix converting Pbs to Unlit material conversion
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2ThermalCamera.cc
Labels: 🔮 dome

#231 4.3.1
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#228 Fix Windows regresion on OgreLightVisual
  include/ignition/rendering/base/BaseLightVisual.hh
  ogre/include/ignition/rendering/ogre/OgreHeightmap.hh
  ogre/include/ignition/rendering/ogre/OgreLightVisual.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreLightVisual.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2LightVisual.hh
Labels: Windows, tests, 🏢 edifice

#234 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#233 Added Light Intensity
  include/ignition/rendering/Light.hh
  include/ignition/rendering/base/BaseLight.hh
  ogre/include/ignition/rendering/ogre/OgreLight.hh
  ogre/src/OgreLight.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Light.hh
  ogre2/src/Ogre2Light.cc
  src/Light_TEST.cc
Labels: needs upstream release, 🏢 edifice

#229 Support setting horizontal and vertical resolution for GpuRays
  include/ignition/rendering/GpuRays.hh
  include/ignition/rendering/base/BaseGpuRays.hh
  test/integration/gpu_rays.cc
Labels: 🏢 edifice

#238 ⬆️ 3.4.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#235 Add support for 8 bit thermal camera image format
  Changelog.md
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/materials/programs/heat_signature_fs.glsl
  ogre2/src/media/materials/programs/thermal_camera_fs.glsl
  test/integration/thermal_camera.cc
Labels: enhancement, 🔮 dome

#242 4 4 0 prep
  CMakeLists.txt
  Changelog.md
  ogre/include/ignition/rendering/ogre/OgreMaterialSwitcher.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTargetMaterial.hh
  ogre2/src/Ogre2GpuRays.cc
Labels: 🔮 dome

#236 More verbose messages when failing to load render engine
  src/RenderEngineManager.cc
Labels: 🏰 citadel

#239 Fixed OBJ textures
  ogre2/src/Ogre2Material.cc
Labels: bug, 🏰 citadel

#245 3 ➡️ 4
  ogre2/src/Ogre2Material.cc
  src/RenderEngineManager.cc
Labels: 🔮 dome

#203 Added Ellipsoid Geometry
  examples/simple_demo/Main.cc
  include/ignition/rendering/Scene.hh
Labels: needs upstream release, 🏢 edifice

#250 Removed issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🔮 dome

#241 Fix setting particle size
  examples/particles_demo/Main.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh
  ogre2/src/Ogre2ParticleEmitter.cc
Labels: ogre2.x, 🔮 dome

#246 4 ➡️ 5
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
  Changelog.md
  examples/gazebo_scene_viewer/SceneManager.hh
  include/ignition/rendering/ArrowVisual.hh
  include/ignition/rendering/AxisVisual.hh
  include/ignition/rendering/Camera.hh
  include/ignition/rendering/CompositeVisual.hh
  include/ignition/rendering/Geometry.hh
  include/ignition/rendering/Image.hh
  include/ignition/rendering/Light.hh
  include/ignition/rendering/Material.hh
  include/ignition/rendering/Mesh.hh
  include/ignition/rendering/Node.hh
  include/ignition/rendering/OrbitViewController.hh
  include/ignition/rendering/RenderEngine.hh
  include/ignition/rendering/RenderEngineManager.hh
  include/ignition/rendering/RenderTarget.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/Storage.hh
  include/ignition/rendering/ViewController.hh
  include/ignition/rendering/Visual.hh
  ogre/include/ignition/rendering/ogre/OgreMaterialSwitcher.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTargetMaterial.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2GpuRays.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_2nd_pass_fs.glsl
  ogre2/src/media/materials/programs/heat_signature_fs.glsl
  ogre2/src/media/materials/programs/thermal_camera_fs.glsl
  ogre2/src/media/materials/scripts/gpu_rays.material
  ogre2/src/media/materials/scripts/thermal.material
  src/RenderEngineManager.cc
  test/integration/gpu_rays.cc
  test/integration/thermal_camera.cc
  test/media/materials/textures/gray_texture.png
Labels: 🏢 edifice

#240 Make particle emitter invisible in thermal camera image
  ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh
  ogre2/src/Ogre2ParticleEmitter.cc
  ogre2/src/Ogre2ThermalCamera.cc
  test/integration/thermal_camera.cc
Labels: ogre2.x, 🔮 dome

#252 Apply particle scattering effect to lidars
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_2nd_pass_fs.glsl
  ogre2/src/media/materials/scripts/gpu_rays.material
  test/integration/gpu_rays.cc
Labels: ogre2.x, 🔮 dome

#251 Apply particle scattering effect to depth cameras
  ogre2/include/ignition/rendering/ogre2/Ogre2Includes.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2Visual.cc
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_2nd_pass_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  ogre2/src/media/materials/scripts/gpu_rays.material
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
Labels: ogre2.x

#254 4.5.0
  CMakeLists.txt
  Changelog.md
  test/integration/depth_camera.cc
Labels: 🔮 dome

#209 Bump in edifice: ign-common4
  .github/ci/packages.apt
  CMakeLists.txt
  bitbucket-pipelines.yml
  tutorials/02_install.md
  tutorials/03_rendering_plugins.md
Labels: needs upstream release, 🏢 edifice

#255 👩‍🌾 Make GitHub actions tests that are flaky due to display more verbose
  .github/ci/after_make.sh
  ogre2/src/Ogre2RenderEngine.cc
  test/integration/camera.cc
Labels: tests, 🏰 citadel

#257 👩‍🌾 3 ➡️ 4
  .github/ci/after_make.sh
  ogre2/src/Ogre2RenderEngine.cc
  test/integration/camera.cc
Labels: 🔮 dome

#258 👩‍🌾 4 ➡️ 5
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
  .github/ci/after_make.sh
  Changelog.md
  examples/particles_demo/Main.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Includes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2ParticleEmitter.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2ParticleEmitter.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/Ogre2Visual.cc
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_2nd_pass_fs.glsl
  ogre2/src/media/materials/scripts/depth_camera.material
  ogre2/src/media/materials/scripts/gpu_rays.material
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
  test/integration/thermal_camera.cc
Labels: 🏢 edifice
