Repository gazebosim/gz-rendering, pull requests merged in 2021-01, with the labels that each got.

#188 Added render order to material
  CMakeLists.txt
  examples/simple_demo/Main.cc
  include/ignition/rendering/Material.hh
  include/ignition/rendering/MeshDescriptor.hh
  include/ignition/rendering/base/BaseMaterial.hh
  ogre/include/ignition/rendering/ogre/OgreMaterial.hh
  ogre/src/OgreMaterial.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/src/Ogre2Material.cc
  tutorials.md.in
  tutorials/21_render_order.md
  tutorials/img/render_order_bad.png
  tutorials/img/render_order_good.png
Labels: needs upstream release, 🔮 dome

#196 Add Windows installation
  README.md
  tutorials/02_install.md
Labels: 🏰 citadel

#204 Call XCloseDisplay in screenScalingFactor
  src/Utils.cc
Labels: 🔮 dome

#207 3 3 0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#208 3 to 4 20210122
  Changelog.md
  README.md
  tutorials/02_install.md
Labels: 🔮 dome

#210 4.2.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#211 Add temperature variations to thermal camera readings based on color
  ogre2/include/ignition/rendering/ogre2/Ogre2Material.hh
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/materials/programs/heat_signature_fs.glsl
  ogre2/src/media/materials/programs/thermal_camera_fs.glsl
Labels: enhancement, 🔮 dome

#195 Tutorial: Transform FBX to Collada and change its origin
  tutorials.md.in
  tutorials/21_transform_fbx_to_dae.md
  tutorials/img/transform_fbx_to_dae/edit_origin.gif
  tutorials/img/transform_fbx_to_dae/import_model.gif
  tutorials/img/transform_fbx_to_dae/remove_elemets.gif
Labels: documentation, 🔮 dome

#215 Revert IgnOGRE Windows fix, it breaks downstream libraries
  ogre/src/CMakeLists.txt
Labels: Windows, bug, 🏰 citadel

#216 3 ➡️ 4
  ogre/src/CMakeLists.txt
Labels: Windows, bug, 🔮 dome

#219 4 ➡️ 5
  ogre/src/CMakeLists.txt
Labels: 🏢 edifice

#220 Fixed spelling Desconstructor -> Destructor
  examples/gazebo_scene_viewer/SceneManager.hh
  include/ignition/rendering/ArrowVisual.hh
  include/ignition/rendering/AxisVisual.hh
  include/ignition/rendering/Camera.hh
  include/ignition/rendering/CompositeVisual.hh
  include/ignition/rendering/Geometry.hh
  include/ignition/rendering/Image.hh
  include/ignition/rendering/Light.hh
  include/ignition/rendering/Material.hh
  include/ignition/rendering/Mesh.hh
  include/ignition/rendering/Node.hh
  include/ignition/rendering/OrbitViewController.hh
  include/ignition/rendering/RenderEngine.hh
  include/ignition/rendering/RenderEngineManager.hh
  include/ignition/rendering/RenderTarget.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/Storage.hh
  include/ignition/rendering/ViewController.hh
  include/ignition/rendering/Visual.hh
Labels: documentation, 🔮 dome

#180 Heightmap for Ogre 1
  CMakeLists.txt
  examples/heightmap/CMakeLists.txt
  examples/heightmap/GlutWindow.cc
  examples/heightmap/GlutWindow.hh
  examples/heightmap/Main.cc
  examples/heightmap/example_config.hh.in
  examples/heightmap/media/city_terrain.jpg
  examples/heightmap/media/dirt_diffusespecular.png
  examples/heightmap/media/flat_normal.png
  examples/heightmap/media/fungus_diffusespecular.png
  examples/heightmap/media/grass_diffusespecular.png
  examples/heightmap/media/heightmap_bowl.png
  include/ignition/rendering/Heightmap.hh
  include/ignition/rendering/HeightmapDescriptor.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseHeightmap.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreCamera.hh
  ogre/include/ignition/rendering/ogre/OgreHeightmap.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreCamera.cc
  ogre/src/OgreHeightmap.cc
  ogre/src/OgreScene.cc
  ogre/src/OgreVisual.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Scene.cc
  src/CMakeLists.txt
  src/HeightmapDescriptor.cc
  src/Heightmap_TEST.cc
  src/base/BaseScene.cc
  test/CMakeLists.txt
  test/media/heightmap_bowl.png
  test/media/materials/textures/flat_normal.png
  tutorials.md.in
  tutorials/21_heightmap.md
  tutorials/img/heightmaps.png
Labels: close the gap, enhancement, 🏢 edifice
