Repository gazebosim/gz-rendering, pull requests merged in 2021-12, with the labels that each got.

#446 Fix selection buffer crash after resizing window
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/media/materials/programs/GLSL/selection_buffer_fs.glsl
  ogre2/src/media/materials/scripts/selection_buffer.material
  src/Utils.cc
  src/Utils_TEST.cc
  test/integration/camera.cc
  test/integration/scene.cc
Labels: bug, 🏯 fortress

#498 Update Metal depth camera and selection buffer shaders to match #446
  ogre2/src/media/materials/programs/Metal/depth_camera_final_fs.metal
  ogre2/src/media/materials/programs/Metal/selection_buffer_fs.metal
Labels: 🏯 fortress

#501 Partial fix for emissive map
  ogre2/src/Ogre2Material.cc
Labels: 🏯 fortress

#415 Fix Ogre2 assertions during ray queries
  include/ignition/rendering/RayQuery.hh
  include/ignition/rendering/base/BaseRayQuery.hh
  ogre/include/ignition/rendering/ogre/OgreRayQuery.hh
  ogre/src/OgreRayQuery.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2RayQuery.hh
  ogre2/src/Ogre2RayQuery.cc
Labels: 🌱 garden

#490 [ogre1.x] Add support for wide angle camera
  examples/wide_angle_camera/CMakeLists.txt
  examples/wide_angle_camera/GlutWindow.cc
  examples/wide_angle_camera/GlutWindow.hh
  examples/wide_angle_camera/Main.cc
  include/ignition/rendering/CameraLens.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/WideAngleCamera.hh
  include/ignition/rendering/base/BaseScene.hh
  include/ignition/rendering/base/BaseWideAngleCamera.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/include/ignition/rendering/ogre/OgreWideAngleCamera.hh
  ogre/src/OgreScene.cc
  ogre/src/OgreWideAngleCamera.cc
  ogre/src/media/materials/programs/wide_lens_map_fp.glsl
  ogre/src/media/materials/programs/wide_lens_map_vs.glsl
  ogre/src/media/materials/scripts/wide_angle_camera.material
  ogre/src/media/materials/scripts/wide_camera_lens_map.compositor
  src/CameraLens.cc
  src/base/BaseScene.cc
  test/integration/CMakeLists.txt
  test/integration/wide_angle_camera.cc
Labels: enhancement, ogre1.x, 🌱 garden

#494 Per-point colors in point clouds
  ogre2/include/ignition/rendering/ogre2/Ogre2DynamicRenderable.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2DynamicRenderable.cc
  ogre2/src/Ogre2LidarVisual.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/media/materials/programs/GLSL/point_fs.glsl
  ogre2/src/media/materials/programs/GLSL/point_vs.glsl
  ogre2/src/media/materials/programs/GLSL/selection_buffer_fs.glsl
  ogre2/src/media/materials/scripts/selection_buffer.material
  src/Utils.cc
  src/Utils_TEST.cc
  test/integration/camera.cc
  test/integration/scene.cc
Labels: enhancement, 🌱 garden

#503 Fix loading grayscale emissive map
  ogre2/src/Ogre2Material.cc
Labels: 🏯 fortress

#507 6 ➡️ 7 (main)
  ogre2/src/Ogre2Material.cc
  ogre2/src/media/materials/programs/Metal/depth_camera_final_fs.metal
  ogre2/src/media/materials/programs/Metal/selection_buffer_fs.metal
Labels: 🌱 garden

#509 Check for OpenGL backend before calling GL APIs
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2LidarVisual.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2ThermalCamera.cc
Labels: 🏯 fortress

#510 Enable selection buffer based ray query (ogre2)
  ogre2/src/Ogre2RayQuery.cc
  src/Utils_TEST.cc
Labels: 🏯 fortress

#511 🎈 6.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#514 RenderOrder is in different scale in Reverse Z
  ogre2/src/Ogre2Material.cc
Labels: 🏯 fortress

#513 6 -> main
  Changelog.md
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2LidarVisual.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2ThermalCamera.cc
  src/Utils_TEST.cc
Labels: 🌱 garden

#515 Fix sky background in RGBD camera
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/media/materials/programs/GLSL/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal
Labels: 🏯 fortress

#518 🎈 4.9.1
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#502 Port Camera Distortion effect from gazebo11
  examples/render_pass/Main.cc
  include/ignition/rendering/DistortionPass.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/base/BaseDistortionPass.hh
  ogre/include/ignition/rendering/ogre/OgreDistortionPass.hh
  ogre/src/OgreDistortionPass.cc
  ogre/src/media/materials/programs/camera_distortion_map_fs.glsl
  ogre/src/media/materials/programs/camera_distortion_map_vs.glsl
  ogre/src/media/materials/scripts/distortion.compositor
  ogre/src/media/materials/scripts/distortion.material
  src/DistortionPass.cc
  test/integration/render_pass.cc
Labels: 🏯 fortress

#519 Fix color of last / extra marker points
  ogre2/src/Ogre2DynamicRenderable.cc
Labels: bug, 🌱 garden

#525 Bumps in garden: use ign-common5, ign-math7
  .github/ci/packages.apt
  CMakeLists.txt
  examples/depth_camera/CMakeLists.txt
  include/ignition/rendering/LidarVisual.hh
  include/ignition/rendering/Marker.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseCamera.hh
  include/ignition/rendering/base/BaseJointVisual.hh
  include/ignition/rendering/base/BaseScene.hh
  src/OrbitViewController.cc
  src/OrthoViewController.cc
  src/TransformController.cc
  src/base/BaseScene.cc
  tutorials/02_install.md
  tutorials/23_depth_camera_tutorial.md
Labels: 🌱 garden
