Repository gazebosim/gz-rendering, pull requests merged in 2021-05, with the labels that each got.

#316 Fix depth alpha
  test/integration/depth_camera.cc
  test/integration/render_pass.cc
Labels: 🔮 dome

#318 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#320 Helper function to get a scene
  include/ignition/rendering/RenderingIface.hh
  ogre/src/OgreRenderEngine.cc
  src/RenderingIface.cc
  src/RenderingIface_TEST.cc
Labels: 🏰 citadel

#294 [OGRE 1.x] Uniform buffer shader support
  examples/custom_shaders_uniforms/CMakeLists.txt
  examples/custom_shaders_uniforms/GlutWindow.cc
  examples/custom_shaders_uniforms/GlutWindow.hh
  examples/custom_shaders_uniforms/Main.cc
  examples/custom_shaders_uniforms/example_config.hh.in
  examples/custom_shaders_uniforms/media/fragment_shader.glsl
  examples/custom_shaders_uniforms/media/vertex_shader.glsl
  include/ignition/rendering/ShaderParam.hh
  ogre/src/OgreMaterial.cc
  src/ShaderParam.cc
  src/ShaderParam_TEST.cc
Labels: enhancement, 🔮 dome

#321 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
Labels: 🏰 citadel

#311 Include MoveTo Helper class to ign-rendering
  include/ignition/rendering/MoveToHelper.hh
  src/MoveToHelper.cc
  src/MoveToHelper_TEST.cc
Labels: 🏯 fortress

#327 ⬆️ 3.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#328 3 ➡️ 4
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  include/ignition/rendering/MoveToHelper.hh
  include/ignition/rendering/RenderingIface.hh
  ogre/src/OgreRenderEngine.cc
  src/MoveToHelper.cc
  src/MoveToHelper_TEST.cc
  src/RenderingIface.cc
  src/RenderingIface_TEST.cc
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
Labels: 🔮 dome

#324 Destroy material when a mesh is deleted
  ogre/include/ignition/rendering/ogre/OgreMeshFactory.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreMaterial.cc
  ogre/src/OgreMesh.cc
  ogre/src/OgreMeshFactory.cc
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Mesh.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2MeshFactory.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2Mesh.cc
  ogre2/src/Ogre2MeshFactory.cc
  ogre2/src/Ogre2Scene.cc
Labels: 🏯 fortress
