Repository gazebosim/gz-rendering, pull requests merged in 2021-10, with the labels that each got.

#449 Prepare for 6.0.1 patch release
  CMakeLists.txt
  Changelog.md
Labels: beta, 🏯 fortress

#452 ogre: Add missing required Paging component
  CMakeLists.txt
Labels: 🏢 edifice

#448 Added macos instructions
  tutorials/02_install.md
Labels: 🏯 fortress
