Repository gazebosim/gz-rendering, pull requests merged in 2021-03, with the labels that each got.

#256 Fix custom_scene_viewer for macOS
  examples/custom_scene_viewer/DemoWindow.cc
  examples/custom_scene_viewer/ManualSceneDemo.cc
Labels: macOS, 🔮 dome

#261 Improve particle scattering noise
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2ParticleEmitter.cc
  ogre2/src/Ogre2ParticleNoiseListener.cc
  ogre2/src/Ogre2ParticleNoiseListener.hh
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
Labels: 🔮 dome

#262 4.6.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#263 fix(typo): sencod --> second
  ogre/src/OgreGpuRays.cc
  ogre2/src/Ogre2GpuRays.cc
Labels: 🔮 dome

#217 Enable particle emitter depth write in example
  examples/particles_demo/Main.cc
Labels: 🔮 dome

#244 ogre2: explicitly request OpenGL 3.3 core profile context.
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🏢 edifice

#259 Fix gazebo_scene_viewer for macOS and ensure exits cleanly
  examples/gazebo_scene_viewer/CMakeLists.txt
  examples/gazebo_scene_viewer/CameraWindow.cc
  examples/gazebo_scene_viewer/GazeboDemo.cc
  examples/gazebo_scene_viewer/GazeboWorldDemo.cc
  examples/gazebo_scene_viewer/SceneManager.cc
  examples/gazebo_scene_viewer/SceneManagerPrivate.hh
Labels: 🔮 dome

#268 Master branch updates
  .github/workflows/ci.yml
  README.md
Labels: 🏰 citadel

#269 Expose particle scatter ratio parameter
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2ParticleEmitter.cc
  ogre2/src/Ogre2ParticleNoiseListener.cc
  ogre2/src/Ogre2ParticleNoiseListener.hh
  src/ParticleEmitter_TEST.cc
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
Labels: 🔮 dome

#266 Fix overriding ogre2 transparency blend mode
  include/ignition/rendering/base/BaseMaterial.hh
  ogre2/src/Ogre2Material.cc
Labels: bug, 🔮 dome

#271 Fix DepthGaussianNoise test
  test/integration/render_pass.cc
Labels: 🏰 citadel

#243 Handle non-positive object temperatures
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/materials/programs/thermal_camera_fs.glsl
Labels: 🔮 dome

#270 3 ➡️ 4
  .github/workflows/ci.yml
  README.md
  test/integration/render_pass.cc
Labels: 🔮 dome

#274 4.7.0
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#264 4 ➡️ 5
  .github/workflows/ci.yml
  Changelog.md
  README.md
  examples/custom_scene_viewer/DemoWindow.cc
  examples/custom_scene_viewer/ManualSceneDemo.cc
  examples/gazebo_scene_viewer/CMakeLists.txt
  examples/gazebo_scene_viewer/CameraWindow.cc
  examples/gazebo_scene_viewer/GazeboDemo.cc
  examples/gazebo_scene_viewer/GazeboWorldDemo.cc
  examples/gazebo_scene_viewer/SceneManager.cc
  examples/gazebo_scene_viewer/SceneManagerPrivate.hh
  examples/particles_demo/Main.cc
  include/ignition/rendering/base/BaseMaterial.hh
  ogre/src/OgreGpuRays.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2ParticleEmitter.cc
  ogre2/src/Ogre2ParticleNoiseListener.cc
  ogre2/src/Ogre2ParticleNoiseListener.hh
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/materials/programs/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/gpu_rays_1st_pass_fs.glsl
  ogre2/src/media/materials/programs/thermal_camera_fs.glsl
  src/ParticleEmitter_TEST.cc
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
  test/integration/render_pass.cc
Labels: beta, 🏢 edifice

#200 Added capsule geometry
  examples/gazebo_scene_viewer/SceneManager.cc
  examples/gazebo_scene_viewer/SceneManagerPrivate.hh
  examples/simple_demo/Main.cc
  include/ignition/rendering/Capsule.hh
  include/ignition/rendering/Marker.hh
  include/ignition/rendering/RenderTypes.hh
  include/ignition/rendering/Scene.hh
  include/ignition/rendering/base/BaseCapsule.hh
  include/ignition/rendering/base/BaseScene.hh
  ogre/include/ignition/rendering/ogre/OgreCapsule.hh
  ogre/include/ignition/rendering/ogre/OgreRenderTypes.hh
  ogre/include/ignition/rendering/ogre/OgreScene.hh
  ogre/src/OgreCapsule.cc
  ogre/src/OgreMarker.cc
  ogre/src/OgreScene.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Capsule.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Capsule.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2Scene.cc
  src/Capsule_TEST.cc
  src/Marker_TEST.cc
  src/base/BaseScene.cc
Labels: beta, 🏢 edifice

#275 Add API for particle emitter scatter ratio
  include/ignition/rendering/ParticleEmitter.hh
  include/ignition/rendering/base/BaseParticleEmitter.hh
  ogre2/src/Ogre2ParticleNoiseListener.cc
  ogre2/src/Ogre2ParticleNoiseListener.hh
  src/ParticleEmitter_TEST.cc
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
Labels: beta, 🏢 edifice

#278 Fix crash on shutdown
  ogre2/src/Ogre2Node.cc
Labels: beta, bug, 🏢 edifice

#280 🎈 5.0.0~pre1
  Changelog.md
Labels: beta, 🏢 edifice

#284 Scale light intensity by PI for Ogre2
  ogre2/src/Ogre2Light.cc
  src/Light_TEST.cc
Labels: beta, bug, 🏢 edifice

#288 Update particles tutorial gif
  tutorials/img/particles.gif
Labels: 🏢 edifice

#287 Update simple demo tutorial gif
  tutorials/img/simple_demo.gif
Labels: documentation, 🏢 edifice

#286 Update README
  README.md
Labels: documentation, 🏢 edifice

#277 Added command line argument for examples to pick version of Ogre
  examples/actor_animation/Main.cc
  examples/camera_tracking/Main.cc
  examples/custom_scene_viewer/ManualSceneDemo.cc
  examples/gazebo_scene_viewer/GazeboDemo.cc
  examples/gazebo_scene_viewer/GazeboWorldDemo.cc
  examples/lidar_visual/Main.cc
  examples/mesh_viewer/Main.cc
  examples/mouse_picking/Main.cc
  examples/particles_demo/Main.cc
  examples/render_pass/Main.cc
  examples/simple_demo/Main.cc
  examples/thermal_camera/Main.cc
  examples/transform_control/Main.cc
  examples/view_control/Main.cc
Labels: 🔮 dome
