Repository gazebosim/gz-rendering, pull requests merged in 2022-10, with the labels that each got.

#734 Prevent multiple singletons from being instantiated
  examples/hello_world_plugin/HelloWorldPlugin.cc
  include/gz/rendering/RenderEngineManager.hh
  ogre/include/gz/rendering/ogre/OgreRTShaderSystem.hh
  ogre/include/gz/rendering/ogre/OgreRenderEngine.hh
  ogre/src/OgreRTShaderSystem.cc
  ogre/src/OgreRenderEngine.cc
  ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2RenderEngine.cc
  optix/include/gz/rendering/optix/OptixRenderEngine.hh
  optix/src/OptixRenderEngine.cc
  src/RenderEngineManager.cc
Labels: 🌱 garden

#735 Initialize wide angle camera pixel format
  ogre/src/OgreWideAngleCamera.cc
  test/integration/wide_angle_camera.cc
Labels: 🌱 garden

#736 Improved coverage Arrow and Axis visuals and fixed some warnings
  include/ignition/rendering/base/BaseArrowVisual.hh
  ogre/src/OgreMaterial.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2ArrowVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2AxisVisual.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderTypes.hh
  ogre2/src/Ogre2ArrowVisual.cc
  ogre2/src/Ogre2AxisVisual.cc
  ogre2/src/Ogre2Scene.cc
  src/ArrowVisual_TEST.cc
  src/AxisVisual_TEST.cc
  src/ShaderParams_TEST.cc
Labels: 🏰 citadel

#737 Improved grid coverage
  src/Grid_TEST.cc
Labels: 🏰 citadel

#738 Increased Marker coverage
  src/Marker_TEST.cc
Labels: 🏰 citadel

#741 [Backport Citadel] Increase TransformControl test converage (#668)
  src/TransformController_TEST.cc
Labels: 🏰 citadel

#739 Improved RenderEngine and Mesh coverage
  src/Mesh_TEST.cc
  src/RenderEngine_TEST.cc
  test/media/skeleton/cmu-13_26.bvh
  test/media/skeleton/walk.dae
Labels: 🏰 citadel

#727 From - LuxCore Render Engine Example #505
  examples/lux_core_engine/CMakeLists.txt
  examples/lux_core_engine/GlutWindow.cc
  examples/lux_core_engine/GlutWindow.hh
  examples/lux_core_engine/LuxCoreEngine.cc
  examples/lux_core_engine/LuxCoreEngineCamera.cc
  examples/lux_core_engine/LuxCoreEngineCamera.hh
  examples/lux_core_engine/LuxCoreEngineGeometry.cc
  examples/lux_core_engine/LuxCoreEngineGeometry.hh
  examples/lux_core_engine/LuxCoreEngineLight.cc
  examples/lux_core_engine/LuxCoreEngineLight.hh
  examples/lux_core_engine/LuxCoreEngineMaterial.cc
  examples/lux_core_engine/LuxCoreEngineMaterial.hh
  examples/lux_core_engine/LuxCoreEngineMesh.cc
  examples/lux_core_engine/LuxCoreEngineMesh.hh
  examples/lux_core_engine/LuxCoreEngineMeshFactory.cc
  examples/lux_core_engine/LuxCoreEngineMeshFactory.hh
  examples/lux_core_engine/LuxCoreEngineNode.cc
  examples/lux_core_engine/LuxCoreEngineNode.hh
  examples/lux_core_engine/LuxCoreEngineObject.cc
  examples/lux_core_engine/LuxCoreEngineObject.hh
  examples/lux_core_engine/LuxCoreEngineRenderTarget.cc
  examples/lux_core_engine/LuxCoreEngineRenderTarget.hh
  examples/lux_core_engine/LuxCoreEngineRenderTypes.hh
  examples/lux_core_engine/LuxCoreEngineScene.cc
  examples/lux_core_engine/LuxCoreEngineScene.hh
  examples/lux_core_engine/LuxCoreEngineSensor.cc
  examples/lux_core_engine/LuxCoreEngineSensor.hh
  examples/lux_core_engine/LuxCoreEngineVisual.cc
  examples/lux_core_engine/LuxCoreEngineVisual.hh
  examples/lux_core_engine/Main.cc
  examples/lux_core_engine/README.md
  examples/lux_core_engine/media/duck.dae
  examples/lux_core_engine/media/duck.png
Labels: 🏯 fortress

#749 Suppress Windows warnings
  ogre/include/ignition/rendering/ogre/OgreIncludes.hh
  ogre/src/OgreRenderTarget.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Includes.hh
  ogre2/src/Ogre2DynamicRenderable.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  ogre2/src/Ogre2Mesh.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2SelectionBuffer.cc
  ogre2/src/Ogre2ThermalCamera.cc
Labels: 🏰 citadel

#753 Prepare for 7.1.0 Release
  Changelog.md
Labels: 🌱 garden
