Repository gazebosim/gz-rendering, pull requests merged in 2022-11, with the labels that each got.

#754 Prepare for 7.1.0 Release (second attempt)
  CMakeLists.txt
Labels: 🌱 garden

#748 Improved coverage: MeshDescriptor, Mesh, MoveToHelper, OrbitViewController, PixelFormat and ShadersParams
  examples/text_geom/CMakeLists.txt
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2Grid.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2Scene.cc
  src/Marker_TEST.cc
  src/MeshDescriptor_TEST.cc
  src/Mesh_TEST.cc
  src/MoveToHelper_TEST.cc
  src/OrbitViewController.cc
  src/OrbitViewController_TEST.cc
  src/PixelFormat_TEST.cc
  src/RenderEngineManager_TEST.cc
  src/RenderEngine_TEST.cc
  src/Scene_TEST.cc
  src/ShaderParams_TEST.cc
Labels: 🏰 citadel

#756 Revert exposing camera intrinsics matrix : https://github.com/gazebosim/gz-rendering/pull/700
  include/gz/rendering/Camera.hh
  include/gz/rendering/base/BaseCamera.hh
  ogre/include/gz/rendering/ogre/OgreCamera.hh
  ogre/src/OgreCamera.cc
  ogre2/include/gz/rendering/ogre2/Ogre2Camera.hh
  ogre2/src/Ogre2Camera.cc
  test/common_test/Camera_TEST.cc
Labels: 🌱 garden

#759 3.6.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#758 Enable GPU based ray queries on mac
  ogre2/src/Ogre2RayQuery.cc
Labels: 🌱 garden

#761 Prepare for 7.2.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#760 Fix lidar heightmap detection
  ogre2/src/Ogre2GpuRays.cc
  test/integration/gpu_rays.cc
Labels: bug, 🏯 fortress, 🌱 garden

#765 Fix non-deterministic rendering due to background texture loading
  ogre2/src/Ogre2Scene.cc
Labels: 🏯 fortress

#762 Enable Heightmap Test for ogre2 & fix crash when using GpuRays camera
  ogre2/src/media/Hlms/Terra/GLSL/VertexShader_vs.glsl
  test/common_test/Heightmap_TEST.cc
Labels: 🌱 garden

#766 Use proper sRGB conversion in DepthCamera
  ogre2/src/media/materials/programs/GLSL/depth_camera_fs.glsl
  ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal
Labels: 🏯 fortress

#767 Disable flaky VisualAt test on mac
  test/integration/scene.cc
Labels: 🌱 garden

#768 3.7.0 prerelease
  CMakeLists.txt
Labels: 🏰 citadel

#770 3.7.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#764 Implement consistent Auto Aspect Ratio
  include/gz/rendering/Camera.hh
  include/gz/rendering/base/BaseCamera.hh
  ogre/include/gz/rendering/ogre/OgreCamera.hh
  ogre/src/OgreCamera.cc
  ogre/src/OgreDepthCamera.cc
  ogre/src/OgreThermalCamera.cc
  ogre2/include/gz/rendering/ogre2/Ogre2Camera.hh
  ogre2/src/Ogre2BoundingBoxCamera.cc
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2SegmentationCamera.cc
  ogre2/src/Ogre2ThermalCamera.cc
  test/common_test/Camera_TEST.cc
  test/integration/camera.cc
Labels: 🌱 garden
