Repository gazebosim/gz-rendering, pull requests merged in 2022-08, with the labels that each got.

#696 Backport 5 :arrow_right: 3 Disabling flaky depth and thermal camera tests on mac (#405)
  test/integration/depth_camera.cc
  test/integration/thermal_camera.cc
Labels: 🏰 citadel, tests, macOS

#698 Destroy GpuRay camera on exit
  ogre2/src/Ogre2GpuRays.cc
Labels: bug, 🌱 garden

#707 Backport from 6 :arrow_right: 3 - Disable C4275 warnings on Windows from OgreUTFString (#621)
  ogre/include/ignition/rendering/ogre/OgreIncludes.hh
  ogre/src/OgreRenderTarget.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2RenderTarget.cc
Labels: 🏰 citadel, Windows, QA

#709 Hotfix typo in ogre2 include statement
  ogre2/include/ignition/rendering/ogre2/Ogre2BoundingBoxCamera.hh
Labels: bug, 🌱 garden

#703 Fix INTEGRATION_camera/shader_selection on macOS
  test/integration/camera.cc
  test/media/materials/programs/simple_color_fs.metal
  test/media/materials/programs/simple_color_vs.metal
Labels: tests, macOS, 🌱 garden, QA

#704 Add regression test for multiple engine reloads
  ogre/src/OgreCamera.cc
  ogre/src/OgreDepthCamera.cc
  ogre/src/OgreGpuRays.cc
  ogre/src/OgreRenderTarget.cc
  ogre/src/OgreThermalCamera.cc
  ogre/src/OgreWideAngleCamera.cc
  test/common_test/CommonRenderingTest.hh
  test/common_test/Material_TEST.cc
  test/regression/CMakeLists.txt
  test/regression/reload_engine.cc
Labels: bug, 🌱 garden
