Repository gazebosim/gz-rendering, pull requests merged in 2022-06, with the labels that each got.

#637 Merge ign-rendering3 ➡️ ign-rendering6
  .github/CODEOWNERS
Labels: 🏯 fortress

#636 Camera::HFOV override for Ogre and Ogre2
  ogre/include/ignition/rendering/ogre/OgreCamera.hh
  ogre/src/OgreCamera.cc
  ogre2/include/ignition/rendering/ogre2/Ogre2Camera.hh
  ogre2/src/Ogre2Camera.cc
  src/Camera_TEST.cc
Labels: 🏯 fortress, OOBE 📦✨

#644 Use pose multiplication instead of subtraction
  include/gz/rendering/base/BaseNode.hh
Labels: 🌱 garden

#639 ign -> gz Environment Variable Migration : gz-rendering
  Migration.md
  examples/hello_world_plugin/README.md
  ogre/src/OgreDepthCamera.cc
  ogre/src/OgreMaterial.cc
  ogre/src/OgreRTShaderSystem.cc
  ogre/src/OgreRenderEngine.cc
  ogre2/src/Ogre2RenderEngine.cc
  optix/src/OptixRenderEngine.cc
  src/base/BaseScene.cc
  tutorials/03_rendering_plugins.md
Labels: 🌱 garden, ign to gz

#635 Change aspect to AspectRatio()
  include/ignition/rendering/base/BaseCamera.hh
  ogre/src/OgreCamera.cc
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2ThermalCamera.cc
  src/Camera_TEST.cc
Labels: 🏯 fortress, OOBE 📦✨

#647 Force scaling factor to be 1.0
  src/Utils.cc
Labels: 🏰 citadel

#650 add missing utility include for std::exchange
  include/ignition/rendering/BoundingBox.hh
Labels: 🏯 fortress

#652 [ign -> gz] CMake functions
  CMakeLists.txt
  include/gz/rendering/CMakeLists.txt
  include/gz/rendering/base/CMakeLists.txt
  ogre/include/gz/rendering/CMakeLists.txt
  ogre/src/CMakeLists.txt
  ogre2/include/gz/rendering/CMakeLists.txt
  ogre2/src/CMakeLists.txt
  optix/include/gz/rendering/CMakeLists.txt
  optix/src/CMakeLists.txt
  src/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#655 Protect against non-finite inputs on Node and OrbitViewController
  include/ignition/rendering/base/BaseNode.hh
  ogre2/src/Ogre2RayQuery.cc
  src/OrbitViewController.cc
Labels: bug, 🏯 fortress

#645 Rename CMake project to gz
  CMakeLists.txt
  Migration.md
  examples/actor_animation/CMakeLists.txt
  examples/camera_tracking/CMakeLists.txt
  examples/custom_scene_viewer/CMakeLists.txt
  examples/custom_shaders/CMakeLists.txt
  examples/custom_shaders_uniforms/CMakeLists.txt
  examples/depth_camera/CMakeLists.txt
  examples/gazebo_scene_viewer/CMakeLists.txt
  examples/heightmap/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/lidar_visual/CMakeLists.txt
  examples/mesh_viewer/CMakeLists.txt
  examples/mouse_picking/CMakeLists.txt
  examples/ogre2_demo/CMakeLists.txt
  examples/particles_demo/CMakeLists.txt
  examples/render_pass/CMakeLists.txt
  examples/segmentation_camera/CMakeLists.txt
  examples/simple_demo/CMakeLists.txt
  examples/simple_demo_qml/CMakeLists.txt
  examples/simple_demo_qml/Main.qml
  examples/text_geom/CMakeLists.txt
  examples/thermal_camera/CMakeLists.txt
  examples/transform_control/CMakeLists.txt
  examples/view_control/CMakeLists.txt
  examples/visualization_demo/CMakeLists.txt
  examples/waves/CMakeLists.txt
  examples/wide_angle_camera/CMakeLists.txt
  ogre/src/CMakeLists.txt
  ogre2/src/CMakeLists.txt
  optix/src/CMakeLists.txt
  src/CMakeLists.txt
  src/RenderEngineManager.cc
  test/CMakeLists.txt
  tutorials/23_depth_camera_tutorial.md
Labels: needs upstream release, 🌱 garden, ign to gz

#656 Migrate IGNITION- CMake variables
  CMakeLists.txt
  examples/actor_animation/CMakeLists.txt
  examples/camera_tracking/CMakeLists.txt
  examples/custom_scene_viewer/CMakeLists.txt
  examples/custom_shaders/CMakeLists.txt
  examples/custom_shaders_uniforms/CMakeLists.txt
  examples/depth_camera/CMakeLists.txt
  examples/gazebo_scene_viewer/CMakeLists.txt
  examples/heightmap/CMakeLists.txt
  examples/lidar_visual/CMakeLists.txt
  examples/mesh_viewer/CMakeLists.txt
  examples/mouse_picking/CMakeLists.txt
  examples/ogre2_demo/CMakeLists.txt
  examples/particles_demo/CMakeLists.txt
  examples/render_pass/CMakeLists.txt
  examples/segmentation_camera/CMakeLists.txt
  examples/simple_demo/CMakeLists.txt
  examples/simple_demo_qml/CMakeLists.txt
  examples/text_geom/CMakeLists.txt
  examples/thermal_camera/CMakeLists.txt
  examples/transform_control/CMakeLists.txt
  examples/view_control/CMakeLists.txt
  examples/visualization_demo/CMakeLists.txt
  examples/waves/CMakeLists.txt
  examples/wide_angle_camera/CMakeLists.txt
Labels: 🌱 garden
