Repository gazebosim/gz-rendering, pull requests merged in 2022-05, with the labels that each got.

#616 Add repo specific issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🏯 fortress

#623 Cleanup depth camera resources on destroy
  ogre2/src/Ogre2DepthCamera.cc
Labels: 🏯 fortress

#624 Use gz-utils test macros
  src/Heightmap_TEST.cc
Labels: 🏯 fortress

#626 Prepare for 6.4.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#630 Merge ign-rendering3 ➡️ ign-rendering6
  .github/CODEOWNERS
Labels: 🏯 fortress

#631 ign -> gz File Move for IgnHlms
  Migration.md
  ogre2/include/gz/rendering/ogre2/Ogre2GzOgreRenderingMode.hh
  ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2GzHlmsPbsPrivate.cc
  ogre2/src/Ogre2GzHlmsPbsPrivate.hh
  ogre2/src/Ogre2GzHlmsSharedPrivate.cc
  ogre2/src/Ogre2GzHlmsSharedPrivate.hh
  ogre2/src/Ogre2GzHlmsSphericalClipMinDistance.cc
  ogre2/src/Ogre2GzHlmsSphericalClipMinDistance.hh
  ogre2/src/Ogre2GzHlmsTerraPrivate.cc
  ogre2/src/Ogre2GzHlmsTerraPrivate.hh
  ogre2/src/Ogre2GzHlmsUnlitPrivate.cc
  ogre2/src/Ogre2GzHlmsUnlitPrivate.hh
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/media/Hlms/Ignition/Pbs/500.IgnPbsStructs_piece_all.any
Labels: 🌱 garden, ign to gz

#632 Suppress new Jammy warnings
  ogre/src/OgreMaterial.cc
  ogre2/src/Ogre2Material.cc
  src/Heightmap_TEST.cc
  src/ShaderParams_TEST.cc
Labels: 🌱 garden

#634 Removed WilliamLewww from Codeowners
  .github/CODEOWNERS
Labels: 🏰 citadel
