Repository gazebosim/gz-rendering, pull requests merged in 2022-07, with the labels that each got.

#665 Ensure one texture per selection buffer per camera.
  ogre2/src/Ogre2SelectionBuffer.cc
  src/RayQuery_TEST.cc
Labels: 🌱 garden, MBARI-LRAUV

#678 Fixed waves example CMakeLists.txt
  examples/waves/CMakeLists.txt
Labels: 🏯 fortress

#682 3 ➡️ 6
  CMakeLists.txt
  README.md
  src/Utils.cc
Labels: 🏯 fortress

#672 ign -> gz Provisional Finale: Source Migration : gz-rendering
  Changelog.md
  Migration.md
  include/gz/rendering/base/base.hh.in
  include/gz/rendering/rendering.hh.in
  ogre/include/gz/rendering/ogre/OgreConversions.hh
  ogre/include/gz/rendering/ogre/OgreRTShaderSystem.hh
  ogre/include/gz/rendering/ogre/ogre.hh.in
  ogre/src/CMakeLists.txt
  ogre/src/OgreHeightmap.cc
  ogre2/include/gz/rendering/ogre2/Ogre2Conversions.hh
  ogre2/include/gz/rendering/ogre2/Ogre2GzOgreRenderingMode.hh
  ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/include/gz/rendering/ogre2/ogre2.hh.in
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2GzHlmsPbsPrivate.cc
  ogre2/src/Ogre2GzHlmsPbsPrivate.hh
  ogre2/src/Ogre2GzHlmsSharedPrivate.hh
  ogre2/src/Ogre2GzHlmsSphericalClipMinDistance.cc
  ogre2/src/Ogre2GzHlmsTerraPrivate.cc
  ogre2/src/Ogre2GzHlmsTerraPrivate.hh
  ogre2/src/Ogre2GzHlmsUnlitPrivate.cc
  ogre2/src/Ogre2GzHlmsUnlitPrivate.hh
  ogre2/src/Ogre2Heightmap.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/Hlms/Gz/SolidColor/500.GzSolidColorStructs_piece_all.any
  ogre2/src/media/Hlms/Gz/SolidColor/800.GzSolidColor_piece_ps.any
  ogre2/src/media/Hlms/Gz/SolidColor/800.GzSolidColor_piece_vs.any
  ogre2/src/media/Hlms/Gz/SphericalClipMinDistance/GzSphericalClipMinDistance_piece_vs.any
  ogre2/src/media/Hlms/Gz/SphericalClipMinDistance/SphericalClipMinDistanceStructs_piece_all.any
  ogre2/src/media/Hlms/Terra/Any/800.PixelShader_piece_ps.any
  ogre2/src/media/Hlms/Terra/gz/100.gz_CustomWeights_piece_ps.any
  ogre2/src/media/materials/programs/GLSL/plain_color_vs.glsl
  ogre2/src/media/materials/programs/Metal/plain_color_vs.metal
  ogre2/src/media/materials/scripts/gpu_rays.material
  ogre2/src/media/materials/scripts/picker.material
  ogre2/src/media/materials/scripts/thermal.material
  ogre2/src/terrain/Terra/CMakeLists.txt
  ogre2/src/terrain/Terra/include/Terra/Hlms/OgreHlmsTerraDatablock.h
  ogre2/src/terrain/Terra/include/Terra/Terra.h
  ogre2/src/terrain/Terra/src/Hlms/OgreHlmsTerra.cpp
  ogre2/src/terrain/Terra/src/Hlms/OgreHlmsTerraDatablock.cpp
  optix/include/gz/rendering/optix/OptixConversions.hh
  optix/include/gz/rendering/optix/optix.hh.in
Labels: 🌱 garden, ign to gz

#671 Add tests for ShaderType, GraphicsAPI, and DistortionPass
  src/GraphicsAPI_TEST.cc
  src/RenderPassSystem_TEST.cc
  src/ShaderType_TEST.cc
Labels: bug, tests, 🏯 fortress, QA

#670 Enable ogre2 heightmap test
  ogre2/include/ignition/rendering/ogre2/Ogre2Heightmap.hh
  ogre2/src/Ogre2Heightmap.cc
  src/Heightmap_TEST.cc
Labels: tests, 🏯 fortress, QA

#677 Change IGN_DESIGNATION to GZ_DESIGNATION
  CMakeLists.txt
  api.md.in
  test/integration/all_symbols_have_version.bash.in
  tutorials.md.in
Labels: ign to gz

#668 Increase TransformControl test converage
  src/TransformController_TEST.cc
Labels: tests, 🏯 fortress, QA

#673 Update Marker test
  src/LidarVisual_TEST.cc
  src/Marker_TEST.cc
Labels: bug, tests, 🏯 fortress, QA

#686 Fixed CMakeLists.txt in examples
  examples/actor_animation/CMakeLists.txt
  examples/boundingbox_camera/CMakeLists.txt
  examples/camera_tracking/CMakeLists.txt
  examples/custom_scene_viewer/CMakeLists.txt
  examples/custom_shaders_uniforms/CMakeLists.txt
  examples/depth_camera/CMakeLists.txt
  examples/gazebo_scene_viewer/CMakeLists.txt
  examples/heightmap/CMakeLists.txt
  examples/lidar_visual/CMakeLists.txt
  examples/mesh_viewer/CMakeLists.txt
  examples/mouse_picking/CMakeLists.txt
  examples/ogre2_demo/CMakeLists.txt
  examples/particles_demo/CMakeLists.txt
  examples/render_pass/CMakeLists.txt
  examples/segmentation_camera/CMakeLists.txt
  examples/simple_demo/CMakeLists.txt
  examples/simple_demo_qml/CMakeLists.txt
  examples/text_geom/CMakeLists.txt
  examples/thermal_camera/CMakeLists.txt
  examples/transform_control/CMakeLists.txt
  examples/view_control/CMakeLists.txt
  examples/visualization_demo/CMakeLists.txt
  examples/waves/CMakeLists.txt
Labels: 🏯 fortress

#689 Add code coverage ignore file
  CMakeLists.txt
  coverage.ignore.in
Labels: 🏰 citadel, QA

#690 Backport multiple ray queries fix (#665)
  ogre2/src/Ogre2SelectionBuffer.cc
  src/RayQuery_TEST.cc
Labels: 🏯 fortress, mbzirc

#691 Merge ign-rendering2 ➡️ ign-rendering3
  api.md.in
  test/integration/all_symbols_have_version.bash.in
  tutorials.md.in
Labels: 🏰 citadel

#692 Prepare for 6.5.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#693 Merge ign-rendering3 ➡️ ign-rendering6
  CMakeLists.txt
  api.md.in
  coverage.ignore.in
  test/integration/all_symbols_have_version.bash.in
  tutorials.md.in
Labels: 🏯 fortress

#642 Support for textures as binary blobs
  examples/mesh_viewer/Main.cc
  examples/mesh_viewer/media/AmbulanceStretcher.glb
  include/gz/rendering/Material.hh
  include/gz/rendering/base/BaseMaterial.hh
  ogre/include/gz/rendering/ogre/OgreMaterial.hh
  ogre/src/OgreMaterial.cc
  ogre2/include/gz/rendering/ogre2/Ogre2Material.hh
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2Scene.cc
  src/base/BaseScene.cc
  test/common_test/Material_TEST.cc
Labels: enhancement, 🌱 garden, Breaking change
