Repository gazebosim/gz-rendering, pull requests merged in 2022-01, with the labels that each got.

#524 Performance optimization by avoiding unnecessary passes
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2SelectionBuffer.cc
Labels: 🏯 fortress, performance

#523 Fix Ogre2ThermalCamera using garbage depth data
  ogre2/src/Ogre2ThermalCamera.cc
Labels: 🏯 fortress

#522 Fix various issues with Ogre2GpuRays
  ogre2/src/Ogre2GpuRays.cc
Labels: 🏯 fortress

#527 Add test case for zero retro value
  ogre2/src/Ogre2GpuRays.cc
  test/integration/gpu_rays.cc
Labels: 🏯 fortress

#528 Silence CMake policy CMP0072
  CMakeLists.txt
Labels: 🏰 citadel

#529 3 ➡️ 5
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice

#530 5 ➡️ 6
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#517 Port Segmentation Camera material to Hlms pieces
  ogre2/include/ignition/rendering/ogre2/Ogre2IgnOgreRenderingMode.hh
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2IgnHlmsCustomizations.hh
  ogre2/src/Ogre2IgnHlmsPbsPrivate.cc
  ogre2/src/Ogre2IgnHlmsPbsPrivate.hh
  ogre2/src/Ogre2IgnHlmsSharedPrivate.cc
  ogre2/src/Ogre2IgnHlmsSharedPrivate.hh
  ogre2/src/Ogre2IgnHlmsUnlitPrivate.cc
  ogre2/src/Ogre2IgnHlmsUnlitPrivate.hh
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.hh
  ogre2/src/media/Hlms/Ignition/Pbs/500.IgnPbsStructs_piece_all.any
  ogre2/src/media/Hlms/Ignition/Pbs/800.IgnPbsCode_piece_ps.any
  ogre2/src/media/Hlms/Ignition/Pbs/800.IgnPbsCode_piece_vs.any
  ogre2/src/media/Hlms/Ignition/SolidColor/500.IgnSolidColorStructs_piece_all.any
  ogre2/src/media/Hlms/Ignition/SolidColor/800.IgnSolidColor_piece_ps.any
  ogre2/src/media/Hlms/Ignition/SolidColor/800.IgnSolidColor_piece_vs.any
  ogre2/src/media/Hlms/Ignition/SphericalClipMinDistance/IgnSphericalClipMinDistance_piece_vs.any
  ogre2/src/media/Hlms/Ignition/SphericalClipMinDistance/SphericalClipMinDistanceStructs_piece_all.any
  ogre2/src/media/Hlms/Terra/GLSL/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.glsl
  ogre2/src/media/Hlms/Terra/HLSL/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.hlsl
  ogre2/src/media/Hlms/Terra/Metal/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.metal
Labels: 🌱 garden

#531 Bind shader uniforms to constants from ogre
  examples/custom_shaders_uniforms/GlutWindow.cc
  examples/custom_shaders_uniforms/media/vertex_shader_330.glsl
  ogre2/src/Ogre2Material.cc
Labels: 🏯 fortress

#535 [Metal] Fix depth camera sensor
  ogre2/src/media/materials/scripts/depth_camera.material
  ogre2/src/media/materials/scripts/selection_buffer.material
Labels: 🏯 fortress

#533 Fix material switching for objects using shaders (ogre2)
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  test/integration/camera.cc
  test/media/materials/programs/simple_color_330_fs.glsl
  test/media/materials/programs/simple_color_330_vs.glsl
  test/media/materials/programs/simple_color_fs.glsl
  test/media/materials/programs/simple_color_vs.glsl
Labels: 🏯 fortress

#536 Fix crash when hovering the cursor in heightmap.sdf
  ogre2/src/media/Hlms/Terra/GLSL/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.glsl
  ogre2/src/media/Hlms/Terra/HLSL/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.hlsl
  ogre2/src/media/Hlms/Terra/Metal/PbsTerraShadows/PbsTerraShadows_piece_vs_piece_ps.metal
Labels: bug, 🏯 fortress

#534 Rename Ogre2IgnHlmsCustomizations to Ogre2IgnHlmsSphericalClipMinDistance
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2IgnHlmsPbsPrivate.cc
  ogre2/src/Ogre2IgnHlmsPbsPrivate.hh
  ogre2/src/Ogre2IgnHlmsSphericalClipMinDistance.cc
  ogre2/src/Ogre2IgnHlmsSphericalClipMinDistance.hh
  ogre2/src/Ogre2IgnHlmsUnlitPrivate.cc
  ogre2/src/Ogre2IgnHlmsUnlitPrivate.hh
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🌱 garden

#538 Update Migration guide
  Migration.md
Labels: 🌱 garden

#548 Prepare for 6.2.0~pre1 prerelease
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#547 Fix missing terrain shadows casted on objects
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🏯 fortress

#549 [Metal] Fix sky background in RGBD camera to match #515
  ogre2/src/media/materials/programs/Metal/depth_camera_fs.metal
Labels: 🌱 garden

#550 [Metal] Fix per-point colors in point clouds to match #494
  ogre2/src/media/materials/programs/GLSL/point_fs.glsl
  ogre2/src/media/materials/programs/Metal/point_fs.metal
  ogre2/src/media/materials/programs/Metal/point_vs.metal
  ogre2/src/media/materials/scripts/point_cloud_point.material
Labels: 🌱 garden

#541 Add waves
  examples/waves/CMakeLists.txt
  examples/waves/GlutWindow.cc
  examples/waves/GlutWindow.hh
  examples/waves/Main.cc
  examples/waves/example_config.hh.in
  examples/waves/media/GerstnerWaves_fs_330.glsl
  examples/waves/media/GerstnerWaves_vs_330.glsl
  examples/waves/media/mesh.dae
  examples/waves/media/skybox_lowres.dds
  examples/waves/media/wave_normals.dds
  include/ignition/rendering/ShaderParam.hh
  ogre2/src/Ogre2Material.cc
  src/ShaderParam.cc
  src/ShaderParam_TEST.cc
Labels: 🏯 fortress

#551 Prepare for 6.2.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress
