Repository gazebosim/gz-rendering, pull requests merged in 2022-03, with the labels that each got.

#571 Fix sky background compositor setup
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderTarget.cc
Labels: 🏯 fortress

#573 Use pose multiplication instead of addition
  include/ignition/rendering/base/BaseCamera.hh
  include/ignition/rendering/base/BaseJointVisual.hh
  include/ignition/rendering/base/BaseNode.hh
Labels: 🏯 fortress

#572 6 -> 7
  Changelog.md
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2RenderTarget.cc
Labels: 🌱 garden

#574 Do not set shader constants for textures on non-OpenGL graphics API
  ogre2/include/ignition/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🏯 fortress

#575 Fix objects using shaders when there is a lidar in the scene (ogre2)
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  test/integration/camera.cc
Labels: 🏯 fortress

#576 Fix render pass example on ogre2
  examples/render_pass/Main.cc
Labels: 🏯 fortress

#578 Respect vertex shader from low level materials in sensor passes (#544)
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
  ogre2/src/Ogre2ThermalCamera.cc
Labels: 🌱 garden

#579 Fix shaders for other sensors that require material switching (ogre2)
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.hh
  ogre2/src/Ogre2ThermalCamera.cc
  test/integration/camera.cc
Labels: 🏯 fortress

#580 [ogre2] Fix heightmap height and update docs
  examples/heightmap/Main.cc
  include/ignition/rendering/HeightmapDescriptor.hh
  ogre2/src/Ogre2Heightmap.cc
Labels: bug, ogre2.x, 🌱 garden

#583 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  README.md
  include/ignition/rendering/HeightmapDescriptor.hh
  include/ignition/rendering/Mesh.hh
  test/integration/camera.cc
  tutorials/02_install.md
Labels: documentation, tests, 🌱 garden

#588 Fix for #578 on macOS / Metal
  ogre2/src/Ogre2Material.cc
Labels: 🌱 garden

#577 Add Ubuntu Jammy CI
  .github/ci/packages-bionic.apt
  .github/ci/packages-focal.apt
  .github/ci/packages-jammy.apt
  .github/ci/packages.apt
  .github/workflows/ci.yml
  CMakeLists.txt
  ogre2/src/CMakeLists.txt
  ogre2/src/terrain/Terra/CMakeLists.txt
Labels: tests, needs upstream release, 🏯 fortress

#590 Merge part of 6 -> main
  include/ignition/rendering/base/BaseCamera.hh
  include/ignition/rendering/base/BaseJointVisual.hh
  include/ignition/rendering/base/BaseNode.hh
  ogre2/src/Ogre2Material.cc
Labels: 🌱 garden

#592 6 -> main
  .github/ci/packages-bionic.apt
  .github/ci/packages-focal.apt
  .github/ci/packages-jammy.apt
  .github/ci/packages.apt
  .github/workflows/ci.yml
  CMakeLists.txt
  examples/render_pass/Main.cc
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/terrain/Terra/CMakeLists.txt
  test/integration/camera.cc
Labels: 🌱 garden

#593 Don't crash if directly set low level materials are used in sensors
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
  ogre2/src/Ogre2ThermalCamera.cc
  ogre2/src/media/materials/programs/GLSL/point_vs.glsl
  ogre2/src/media/materials/scripts/picker.material
  ogre2/src/media/materials/scripts/picker.program
  ogre2/src/media/materials/scripts/point_cloud_point.material
Labels: 🌱 garden

#594 🏁🎈 5.2.1
  CMakeLists.txt
  Changelog.md
Labels: 🏢 edifice
