Repository gazebosim/gz-rendering, pull requests merged in 2022-04, with the labels that each got.

#599 5 -> 6
  Changelog.md
Labels: 🏯 fortress

#601 Default cameraPassCountPerGpuFlush to 6
  ogre2/src/Ogre2Scene.cc
Labels: 🌱 garden

#584 Use custom simulation time variants for Ogre
  Migration.md
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Scene.cc
  src/Scene_TEST.cc
  src/base/BaseScene.cc
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
Labels: 🏯 fortress

#602 6 -> 7
  Changelog.md
  Migration.md
  ogre2/include/ignition/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Scene.cc
  test/integration/camera.cc
  test/integration/depth_camera.cc
  test/integration/gpu_rays.cc
Labels: 🌱 garden

#595 Separate cache files for each heightmap LOD
  ogre/src/OgreHeightmap.cc
Labels: 🌱 garden

#585 Flip heightmap's Y position on Ogre 2 and add sanity checks for NaN
  Changelog.md
  Migration.md
  examples/heightmap/Main.cc
  ogre/src/OgreHeightmap.cc
  ogre2/src/Ogre2Heightmap.cc
Labels: ogre1.x, ogre2.x, 🏯 fortress, MBARI-LRAUV

#604 Prepare for 6.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#603 6 ➡️ 7 (main)
  Changelog.md
  Migration.md
  examples/heightmap/Main.cc
  ogre/src/OgreHeightmap.cc
  ogre2/src/Ogre2Heightmap.cc
Labels: 🌱 garden, MBARI-LRAUV

#606 Replace deprecated common::SubMesh::MaterialIndex() with GetMaterialIndex()
  ogre/src/OgreMeshFactory.cc
  ogre2/src/Ogre2MeshFactory.cc
  optix/src/OptixMeshFactory.cc
Labels: 🌱 garden

#607 hello_world_plugin: fix find version variables
  examples/hello_world_plugin/CMakeLists.txt
Labels: 🌱 garden

#605 Revert OGRE-Next custom support and back to use IgnOGRE2 module
  .github/ci/packages-bionic.apt
  .github/ci/packages-focal.apt
  .github/ci/packages-jammy.apt
  .github/ci/packages.apt
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: 🏯 fortress

#609 Prepare 6.3.1
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#608 Bumps in garden : ign-rendering7
  .github/ci/packages.apt
  CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  tutorials/02_install.md
Labels: 🌱 garden

#610 Bumps in garden : ign-rendering7
  .github/ci/packages.apt
  CMakeLists.txt
  examples/simple_demo_qml/CMakeLists.txt
  tutorials/02_install.md
Labels: 🌱 garden

#612 Updated CODEOWNERS
  .github/CODEOWNERS
Labels: 🏰 citadel

#613 Fix codeowners
  .github/CODEOWNERS
Labels: 🏰 citadel

#614 6 ➡️ 7 (main)
  CMakeLists.txt
  Changelog.md
  ogre2/src/CMakeLists.txt
  ogre2/src/terrain/Terra/CMakeLists.txt
Labels: 🌱 garden
