Repository gazebosim/gz-rendering, pull requests merged in 2023-09, with the labels that each got.

#891 Prepare for 6.6.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#893 Do not load optix engine in examples
  examples/camera_tracking/Main.cc
  examples/custom_scene_viewer/ManualSceneDemo.cc
  examples/gazebo_scene_viewer/GazeboDemo.cc
  examples/gazebo_scene_viewer/GazeboWorldDemo.cc
  examples/mesh_viewer/Main.cc
  examples/mouse_picking/Main.cc
  examples/projector/Main.cc
  examples/render_pass/Main.cc
  examples/simple_demo/Main.cc
  examples/text_geom/Main.cc
  examples/transform_control/Main.cc
  examples/view_control/Main.cc
  examples/visualization_demo/Main.cc
  examples/wide_angle_camera/Main.cc
  tutorials/17_render_pass_tutorial.md
  tutorials/18_simple_demo_tutorial.md
  tutorials/19_text_geom_tutorial.md
Labels: 🎵 harmonic

#895 Update custom scene viewer tutorial
  tutorials/13_custom_scene_viewer.md
Labels: 🎵 harmonic

#894 Revert mesh viewer background color back to gray
  examples/mesh_viewer/Main.cc
Labels: 🏯 fortress

#889 Fix arrow visual indexing
  Migration.md
  include/gz/rendering/base/BaseArrowVisual.hh
  include/gz/rendering/base/BaseAxisVisual.hh
  test/common_test/ArrowVisual_TEST.cc
Labels: beta, 🎵 harmonic

#896 Fix typo in bounding box camera tutorial
  tutorials/24_boundingbox_camera_tutorial.md
Labels: 🌱 garden

#900 Fix wide angle camera visibility flags
  ogre2/src/Ogre2WideAngleCamera.cc
Labels: 🎵 harmonic

#892 Minor updates to README file in the hello_world_plugin example
  examples/hello_world_plugin/README.md
Labels: 🌱 garden

#903 Disable setting particle emitter color range
  ogre2/src/Ogre2ParticleEmitter.cc
  test/common_test/ParticleEmitter_TEST.cc
Labels: 🌱 garden

#904 Prepare for 8.0.0 pre2 prerelease
  CMakeLists.txt
Labels: 🎵 harmonic

#906 Update installation instructions
  tutorials/02_install.md
Labels: 🎵 harmonic

#897 Fixed build on MSVC
  include/gz/rendering/GlobalIlluminationBase.hh
  include/gz/rendering/GlobalIlluminationCiVct.hh
  include/gz/rendering/GlobalIlluminationVct.hh
  include/gz/rendering/NativeWindow.hh
  include/gz/rendering/base/BaseNativeWindow.hh
  ogre2/include/gz/rendering/ogre2/Ogre2GlobalIlluminationCiVct.hh
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2GlobalIlluminationCiVct.cc
  ogre2/src/Ogre2RenderEngine.cc
  src/GlobalIlluminationBase.cc
  src/GlobalIlluminationCiVct.cc
  src/GlobalIlluminationVct.cc
  src/NativeWindow.cc
  src/base/BaseNativeWindow.cc
Labels: 🎵 harmonic

#909 ogre2: retain CMAKE_INSTALL_RPATH values
  ogre2/src/CMakeLists.txt
Labels: 🎵 harmonic

#911 Include the CGL header on macOS
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🎵 harmonic

#912 Backport #909: rpath fix for garden
  ogre2/src/CMakeLists.txt
Labels: 🌱 garden

#913 Fix projector FOV, orientation, and crashes
  ogre2/src/Ogre2Projector.cc
  ogre2/src/media/Hlms/Terra/GLSL/PixelShader_ps.glsl
  ogre2/src/media/Hlms/Terra/gz/500.gz_Structs_piece_all.any
  test/integration/projector.cc
Labels: beta, 🎵 harmonic

#915 Remove gazebo scene viewer example
  examples/gazebo_scene_viewer/CMakeLists.txt
  examples/gazebo_scene_viewer/CameraWindow.cc
  examples/gazebo_scene_viewer/CameraWindow.hh
  examples/gazebo_scene_viewer/GazeboDemo.cc
  examples/gazebo_scene_viewer/GazeboWorldDemo.cc
  examples/gazebo_scene_viewer/SceneManager.cc
  examples/gazebo_scene_viewer/SceneManager.hh
  examples/gazebo_scene_viewer/SceneManagerPrivate.hh
  examples/gazebo_scene_viewer/falling_objects.world
  tutorials.md.in
  tutorials/11_gazebo_scene_viewer_tutorial.md
Labels: beta, 🎵 harmonic

#905 [backport fortress] Calculate camera intrinsics : Refactor
  include/gz/rendering/Utils.hh
  src/Camera_TEST.cc
  src/Utils.cc
Labels: 🏯 fortress

#921 Merge ign-rendering6 ➡️ gz-rendering7
  Changelog.md
  examples/mesh_viewer/Main.cc
Labels: 🌱 garden

#922 Prepare for 7.4.2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#924 Prepare for 8.0.0~pre3 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#926 Prepare for 8.0.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic
