Repository gazebosim/gz-rendering, pull requests merged in 2023-10, with the labels that each got.

#929 Fix float comparison warnings in test
  src/Camera_TEST.cc
Labels: 🏯 fortress

#930 Prepare for 6.6.2 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#925 Update ci.yml
  .github/workflows/ci.yml
Labels: 🌱 garden

#931 Fix use of srgb format for texture maps (from glb meshes)
  ogre2/src/Ogre2Material.cc
Labels: 🌱 garden

#920 Minor fix to checking projector default visibility flags
  ogre2/src/Ogre2Projector.cc
Labels: 🎵 harmonic

#901 Support skybox in wide angle cam view
  ogre2/include/gz/rendering/ogre2/Ogre2WideAngleCamera.hh
  ogre2/src/Ogre2Scene.cc
  ogre2/src/Ogre2WideAngleCamera.cc
  test/integration/sky.cc
Labels: 🎵 harmonic

#908 Extend ogre 1.x custom shaders support
  examples/waves/GlutWindow.cc
  examples/waves/Main.cc
  examples/waves/media/GerstnerWaves_fs.glsl
  examples/waves/media/GerstnerWaves_vs.glsl
  ogre/src/OgreMaterial.cc
  ogre2/src/Ogre2Material.cc
  test/integration/CMakeLists.txt
  test/integration/waves.cc
  test/media/materials/programs/GerstnerWaves_fs.glsl
  test/media/materials/programs/GerstnerWaves_fs.metal
  test/media/materials/programs/GerstnerWaves_fs_330.glsl
  test/media/materials/programs/GerstnerWaves_vs.glsl
  test/media/materials/programs/GerstnerWaves_vs.metal
  test/media/materials/programs/GerstnerWaves_vs_330.glsl
  test/media/materials/textures/skybox_lowres.dds
  test/media/materials/textures/wave_normals.dds
  test/media/meshes/mesh.dae
Labels: 🌱 garden

#932 Merge: 6 -> 7
  Changelog.md
  test/common_test/Camera_TEST.cc
Labels: 🌱 garden

#933 Merge: 7 -> 8
  .github/workflows/ci.yml
  Changelog.md
  examples/waves/GlutWindow.cc
  examples/waves/Main.cc
  examples/waves/media/GerstnerWaves_fs.glsl
  examples/waves/media/GerstnerWaves_vs.glsl
  ogre/src/OgreMaterial.cc
  ogre2/src/Ogre2Material.cc
  test/common_test/Camera_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/waves.cc
  test/media/materials/programs/GerstnerWaves_fs.glsl
  test/media/materials/programs/GerstnerWaves_fs.metal
  test/media/materials/programs/GerstnerWaves_fs_330.glsl
  test/media/materials/programs/GerstnerWaves_vs.glsl
  test/media/materials/programs/GerstnerWaves_vs.metal
  test/media/materials/programs/GerstnerWaves_vs_330.glsl
  test/media/materials/textures/skybox_lowres.dds
  test/media/materials/textures/wave_normals.dds
  test/media/meshes/mesh.dae
Labels: 🎵 harmonic
