Repository gazebosim/gz-rendering, pull requests merged in 2023-01, with the labels that each got.

#800 Fix selecting semi-transparent visuals
  ogre2/src/Ogre2SelectionBuffer.cc
  src/base/BaseScene.cc
Labels: 🌱 garden

#799 Fix gpu lidar memory leak [ogre2]
  ogre2/src/Ogre2GzHlmsSharedPrivate.cc
  ogre2/src/Ogre2GzHlmsSharedPrivate.hh
Labels: 🌱 garden

#801 6 -> 7
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🌱 garden

#807 Mesh cleanup on destruction
  ogre2/src/Ogre2Mesh.cc
  src/Mesh_TEST.cc
Labels: 🏯 fortress

#808 Prepare for 6.5.2 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#809 Fix duplicate PreRrender calls
  include/ignition/rendering/base/BaseNode.hh
  include/ignition/rendering/base/BaseVisual.hh
  ogre2/src/Ogre2RenderTarget.cc
Labels: 🏯 fortress

#811 Fix transparency over heightmap
  examples/mesh_viewer/Main.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2Mesh.cc
  test/integration/CMakeLists.txt
  test/integration/heightmap.cc
  test/media/materials/textures/blue_texture.png
Labels: 🏯 fortress

#813 Remove fini to resolve segfault at shutdown
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🏰 citadel

#816 Ensure composite BaseVisuals are destroyed correctly.
  include/gz/rendering/base/BaseArrowVisual.hh
  include/gz/rendering/base/BaseAxisVisual.hh
  include/gz/rendering/base/BaseJointVisual.hh
Labels: 🌱 garden
