Repository gazebosim/gz-rendering, pull requests merged in 2023-02, with the labels that each got.

#818 Backport Composite BaseVisual destroy fix to 6
  include/ignition/rendering/base/BaseArrowVisual.hh
  include/ignition/rendering/base/BaseAxisVisual.hh
  include/ignition/rendering/base/BaseJointVisual.hh
Labels: 🏯 fortress

#817 Cleanup GpuRays properly
  ogre/src/OgreGpuRays.cc
  ogre2/src/Ogre2GpuRays.cc
  test/integration/gpu_rays.cc
Labels: 🌱 garden

#820 6.6.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#821 3.7.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#824 Limit max camera node position values
  ogre/src/OgreNode.cc
  ogre2/src/Ogre2Node.cc
Labels: 🏯 fortress

#825 3 -> 6
  Changelog.md
Labels: 🏯 fortress
