Repository gazebosim/gz-rendering, pull requests merged in 2023-08, with the labels that each got.

#878 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#883 Prepare for 7.4.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#886 Clean up internal resources on Destroy
  ogre/src/OgreDistortionPass.cc
  ogre2/include/gz/rendering/ogre2/Ogre2LensFlarePass.hh
  ogre2/src/Ogre2LensFlarePass.cc
  ogre2/src/Ogre2Material.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
Labels: beta, 🎵 harmonic

#888 Remove bionic and focal apt packages for harmonic
  .github/ci/packages-bionic.apt
  .github/ci/packages-focal.apt
Labels: 🎵 harmonic
