Repository gazebosim/gz-rendering, pull requests merged in 2023-03, with the labels that each got.

#826 6 -> 7
  Changelog.md
  ogre/src/OgreNode.cc
  ogre2/src/Ogre2Node.cc
Labels: 🌱 garden

#827 Tweak max camera position limit
  ogre2/src/Ogre2Node.cc
Labels: 🏯 fortress

#828 Prepare for 7.3.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#829 Add message to see troubleshooting page when render engine fails to create dummy window
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🏯 fortress

#831 Use std::vector instead of std::map in BaseStorage
  Migration.md
  include/gz/rendering/base/BaseStorage.hh
  include/gz/rendering/base/BaseVisual.hh
  ogre/src/OgreVisual.cc
  ogre2/src/Ogre2Visual.cc
  test/common_test/Scene_TEST.cc
Labels: 🎵 harmonic

#833 Rename COPYING to LICENSE
  COPYING
  LICENSE
Labels: 🏰 citadel

#834 CI workflow: use checkout v3
  .github/workflows/ci.yml
Labels: 🏰 citadel

#835 Merge ign-rendering3 ➡️ ign-rendering6
  .github/workflows/ci.yml
  COPYING
  LICENSE
Labels: 🏯 fortress

#836 Merge ign-rendering6 ➡️ gz-rendering7
  .github/workflows/ci.yml
  COPYING
  LICENSE
  ogre2/src/Ogre2Node.cc
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🌱 garden

#839 7 -> main
  .github/workflows/ci.yml
  COPYING
  Changelog.md
  LICENSE
  ogre/src/OgreNode.cc
  ogre2/src/Ogre2Node.cc
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🎵 harmonic
