Repository gazebosim/gz-rendering, pull requests merged in 2023-11, with the labels that each got.

#937 Update examples to use metal as default graphics API on mac
  examples/actor_animation/Main.cc
  examples/boundingbox_camera/Main.cc
  examples/camera_tracking/Main.cc
  examples/custom_scene_viewer/ManualSceneDemo.cc
  examples/custom_shaders_uniforms/Main.cc
  examples/depth_camera/Main.cc
  examples/heightmap/Main.cc
  examples/lidar_visual/Main.cc
  examples/mesh_viewer/Main.cc
  examples/mouse_picking/Main.cc
  examples/ogre2_demo/Main.cc
  examples/particles_demo/Main.cc
  examples/projector/Main.cc
  examples/render_pass/Main.cc
  examples/segmentation_camera/Main.cc
  examples/simple_demo/Main.cc
  examples/simple_demo_qml/ThreadRenderer.cpp
  examples/text_geom/Main.cc
  examples/thermal_camera/Main.cc
  examples/transform_control/Main.cc
  examples/view_control/Main.cc
  examples/visualization_demo/Main.cc
  examples/waves/Main.cc
  examples/wide_angle_camera/Main.cc
  include/gz/rendering/Utils.hh
  src/Utils.cc
Labels: 🌱 garden

#939 Update github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🏯 fortress

#881 Add minor comments to BaseGizmoVisual
  include/gz/rendering/base/BaseGizmoVisual.hh
Labels: 🏰 citadel

#942 Merge ign-rendering3 ➡️ ign-rendering6
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  include/gz/rendering/base/BaseGizmoVisual.hh
Labels: 🏯 fortress
