Repository gazebosim/gz-rendering, pull requests merged in 2024-07, with the labels that each got.

#1014 Fix debug builds of gz-rendering-ogre2 plugin
  ogre2/src/CMakeLists.txt
Labels: 🎵 harmonic

#1016 Fix crash when wide angle camera FOV is > 180
  ogre/src/OgreWideAngleCamera.cc
  ogre2/src/Ogre2WideAngleCamera.cc
Labels: 🎵 harmonic

#1017 Fix build fortress + jammy
  include/gz/rendering/GraphicsAPI.hh
Labels: 🏯 fortress

#1022 Optimization: remove extra copy of data buffer in Ogre2GpuRays and Ogre2DepthCamera
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
Labels: 🎵 harmonic

#1020 Remove deprecated functions and enums
  ogre2/include/gz/rendering/ogre2/Ogre2GzOgreRenderingMode.hh
  ogre2/include/gz/rendering/ogre2/Ogre2RenderEngine.hh
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2MaterialSwitcher.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2RenderTarget.cc
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
  ogre2/src/Ogre2ThermalCamera.cc
  src/RenderEngineManager.cc
  src/base/BaseScene.cc
Labels: 🏛️ ionic

#1021 Override SetProjectionMatrix and ProjectionMatrix functions in derived ogre2 camera classes.
  ogre2/include/gz/rendering/ogre2/Ogre2BoundingBoxCamera.hh
  ogre2/include/gz/rendering/ogre2/Ogre2SegmentationCamera.hh
  ogre2/include/gz/rendering/ogre2/Ogre2ThermalCamera.hh
  ogre2/src/Ogre2BoundingBoxCamera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2SegmentationCamera.cc
  ogre2/src/Ogre2ThermalCamera.cc
Labels: 🏛️ ionic

#1024 Update ogre2 ray query related functions to return Ogre::MovableObject instead of Ogre::Item
  Migration.md
  ogre2/include/gz/rendering/ogre2/Ogre2SelectionBuffer.hh
  ogre2/src/Ogre2Camera.cc
  ogre2/src/Ogre2RayQuery.cc
  ogre2/src/Ogre2SelectionBuffer.cc
Labels: 🏛️ ionic

#1023 Disable Unit test that have segfaults on Mac (rendering3)
  src/ArrowVisual_TEST.cc
  src/AxisVisual_TEST.cc
  src/Camera_TEST.cc
  src/Grid_TEST.cc
  src/Light_TEST.cc
  src/Marker_TEST.cc
  src/Material_TEST.cc
  src/Mesh_TEST.cc
  src/MoveToHelper_TEST.cc
  src/Node_TEST.cc
  src/OrbitViewController_TEST.cc
  src/RayQuery_TEST.cc
  src/RenderTarget_TEST.cc
  src/RenderingIface_TEST.cc
  src/Scene_TEST.cc
  src/ThermalCamera_TEST.cc
  src/TransformController_TEST.cc
  src/Visual_TEST.cc
  test/integration/CMakeLists.txt
Labels: 🏰 citadel

#1019 Add gamma correction to simple_demo_qml example
  examples/simple_demo_qml/GzRenderer.cc
  examples/simple_demo_qml/ThreadRenderer.cpp
Labels: beta, 🎵 harmonic

#1025 3 :arrow_right: 6
  src/ArrowVisual_TEST.cc
  src/AxisVisual_TEST.cc
  src/Camera_TEST.cc
  src/Grid_TEST.cc
  src/Light_TEST.cc
  src/Marker_TEST.cc
  src/Material_TEST.cc
  src/Mesh_TEST.cc
  src/MoveToHelper_TEST.cc
  src/Node_TEST.cc
  src/OrbitViewController_TEST.cc
  src/RayQuery_TEST.cc
  src/RenderTarget_TEST.cc
  src/RenderingIface_TEST.cc
  src/Scene_TEST.cc
  src/ThermalCamera_TEST.cc
  src/TransformController_TEST.cc
  src/Visual_TEST.cc
  test/integration/CMakeLists.txt
Labels: 🏯 fortress
