Repository gazebosim/gz-rendering, pull requests merged in 2024-03, with the labels that each got.

#976 Fix setting normal map when not all submeshes have texcoords (ogre2)
  ogre2/src/Ogre2MeshFactory.cc
  test/integration/CMakeLists.txt
  test/integration/mesh.cc
Labels: 🌱 garden

#975 Backport Ogre2DepthCamera performance improvements
  ogre2/src/Ogre2DepthCamera.cc
Labels: 🏯 fortress

#977 Merge 7 -> 8
  ogre2/src/Ogre2MeshFactory.cc
  test/integration/CMakeLists.txt
  test/integration/mesh.cc
Labels: 🎵 harmonic

#978 Backport lidar particle detection optimization
  ogre2/src/Ogre2GpuRays.cc
Labels: 🏯 fortress

#979 Merge 8 -> main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  include/gz/rendering/base/BaseGizmoVisual.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GlobalIlluminationCiVct.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2MeshFactory.cc
  ogre2/src/media/materials/scripts/GpuRays.compositor
  test/integration/CMakeLists.txt
  test/integration/mesh.cc
Labels: 🏛️ ionic

#980 Prepare for 8.1.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#982 Handle null mesh pointers in examples
  examples/actor_animation/Main.cc
  examples/boundingbox_camera/Main.cc
  examples/depth_camera/Main.cc
  examples/global_illumination/Main.cc
  examples/lux_core_engine/Main.cc
  examples/mesh_viewer/Main.cc
  examples/ogre2_demo/Main.cc
  examples/particles_demo/Main.cc
  examples/segmentation_camera/Main.cc
  examples/thermal_camera/Main.cc
  examples/waves/Main.cc
  ogre/src/OgreMeshFactory.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2MeshFactory.cc
  src/base/BaseScene.cc
  test/common_test/MeshDescriptor_TEST.cc
  test/common_test/Mesh_TEST.cc
  test/integration/waves.cc
Labels: 🎵 harmonic
