Repository gazebosim/gz-rendering, pull requests merged in 2024-08, with the labels that each got.

#1026 Merge 6 -> 7 (Partial merge forward)
  ogre/src/OgreDistortionPass.cc
Labels: 🌱 garden

#1027 Merge 7 -> 8
  ogre/src/OgreDistortionPass.cc
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🎵 harmonic

#1029 Merge 8 -> main
  Changelog.md
  examples/simple_demo_qml/GzRenderer.cc
  examples/simple_demo_qml/ThreadRenderer.cpp
  ogre/src/OgreDistortionPass.cc
  ogre/src/OgreWideAngleCamera.cc
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GpuRays.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2WideAngleCamera.cc
  src/ShaderParam.cc
  test/integration/gpu_rays.cc
Labels: 🏛️ ionic

#1028 Disable tests that have segfaults on Mac (rendering6)
  src/Camera_TEST.cc
  src/Capsule_TEST.cc
  src/Heightmap_TEST.cc
  src/JointVisual_TEST.cc
  src/LidarVisual_TEST.cc
  src/LightVisual_TEST.cc
  src/Mesh_TEST.cc
  src/OrthoViewController_TEST.cc
  src/RenderTarget_TEST.cc
  src/Scene_TEST.cc
  src/Text_TEST.cc
  src/Visual_TEST.cc
  src/WireBox_TEST.cc
  test/integration/CMakeLists.txt
Labels: 🏯 fortress

#1030 Update troubleshooting link
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🏛️ ionic

#1031 Remove more deprecated env vars
  ogre/src/OgreDepthCamera.cc
  ogre/src/OgreMaterial.cc
  ogre/src/OgreRTShaderSystem.cc
  ogre/src/OgreRenderEngine.cc
  optix/src/OptixRenderEngine.cc
Labels: 🏛️ ionic

#1032 Hide optix related cmake warnings
  CMakeLists.txt
Labels: 🏛️ ionic

#1035 Install Roboto fonts to ogre plugin
  ogre/src/media/fonts/CMakeLists.txt
  ogre/src/media/fonts/README.md
  ogre/src/media/fonts/gz-rendering.fontdef
  ogre/src/media/fonts/roboto/LICENSE.txt
  ogre/src/media/fonts/roboto/Roboto-Black.ttf
  ogre/src/media/fonts/roboto/Roboto-BlackItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Bold.ttf
  ogre/src/media/fonts/roboto/Roboto-BoldItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Italic.ttf
  ogre/src/media/fonts/roboto/Roboto-Light.ttf
  ogre/src/media/fonts/roboto/Roboto-LightItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Medium.ttf
  ogre/src/media/fonts/roboto/Roboto-MediumItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Regular.ttf
  ogre/src/media/fonts/roboto/Roboto-Thin.ttf
  ogre/src/media/fonts/roboto/Roboto-ThinItalic.ttf
  test/common_test/Text_TEST.cc
Labels: 🎵 harmonic

#1037 Enable 24.04 CI, require cmake 3.22.1
  .github/ci/packages-noble.apt
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  examples/actor_animation/CMakeLists.txt
  examples/boundingbox_camera/CMakeLists.txt
  examples/camera_tracking/CMakeLists.txt
  examples/custom_scene_viewer/CMakeLists.txt
  examples/custom_shaders/CMakeLists.txt
  examples/custom_shaders_uniforms/CMakeLists.txt
  examples/depth_camera/CMakeLists.txt
  examples/global_illumination/CMakeLists.txt
  examples/heightmap/CMakeLists.txt
  examples/hello_world_plugin/CMakeLists.txt
  examples/lidar_visual/CMakeLists.txt
  examples/lux_core_engine/CMakeLists.txt
  examples/mesh_viewer/CMakeLists.txt
  examples/mouse_picking/CMakeLists.txt
  examples/ogre2_demo/CMakeLists.txt
  examples/particles_demo/CMakeLists.txt
  examples/projector/CMakeLists.txt
  examples/render_pass/CMakeLists.txt
  examples/segmentation_camera/CMakeLists.txt
  examples/simple_demo/CMakeLists.txt
  examples/simple_demo_qml/CMakeLists.txt
  examples/text_geom/CMakeLists.txt
  examples/thermal_camera/CMakeLists.txt
  examples/transform_control/CMakeLists.txt
  examples/view_control/CMakeLists.txt
  examples/visualization_demo/CMakeLists.txt
  examples/waves/CMakeLists.txt
  examples/wide_angle_camera/CMakeLists.txt
  test/integration/waves.cc
Labels: 🏛️ ionic

#1036 Fix overloaded virtual warnings on noble
  Migration.md
  include/gz/rendering/Camera.hh
  include/gz/rendering/GpuRays.hh
  include/gz/rendering/Object.hh
  include/gz/rendering/ParticleEmitter.hh
  include/gz/rendering/RenderPass.hh
  include/gz/rendering/RenderTarget.hh
  include/gz/rendering/Visual.hh
  include/gz/rendering/base/BaseParticleEmitter.hh
  include/gz/rendering/base/BaseRenderPass.hh
  include/gz/rendering/base/BaseRenderTarget.hh
  ogre/include/gz/rendering/ogre/OgreRenderTarget.hh
  ogre/src/OgreRenderTarget.cc
  ogre2/include/gz/rendering/ogre2/Ogre2GaussianNoisePass.hh
  ogre2/include/gz/rendering/ogre2/Ogre2ParticleEmitter.hh
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2GaussianNoisePass.cc
  ogre2/src/Ogre2ParticleEmitter.cc
Labels: 🏛️ ionic

#1033 Workaround for ogre crash on shutdown
  ogre/src/OgreRenderEngine.cc
Labels: 🏛️ ionic

#1034 Expose shadow texture size for directional lighting in SDF
  include/gz/rendering/Light.hh
  include/gz/rendering/Scene.hh
  include/gz/rendering/base/BaseScene.hh
  ogre2/include/gz/rendering/ogre2/Ogre2Scene.hh
  ogre2/src/Ogre2Scene.cc
  src/base/BaseScene.cc
  test/common_test/Scene_TEST.cc
Labels: 🎵 harmonic

#1040 Fix segmentation camera color id computation with new math::Color clamping behavior (ogre2)
  ogre2/src/Ogre2SegmentationMaterialSwitcher.cc
Labels: 🏛️ ionic

#1041 Remove setting OpenGL_GL_PREFERENCE in cmake
  CMakeLists.txt
Labels: 🏛️ ionic

#1042 Ionic Changelog
  Changelog.md
Labels: 🏛️ ionic

#1043 Merge 8 -> main
  ogre/src/media/fonts/CMakeLists.txt
  ogre/src/media/fonts/README.md
  ogre/src/media/fonts/gz-rendering.fontdef
  ogre/src/media/fonts/roboto/LICENSE.txt
  ogre/src/media/fonts/roboto/Roboto-Black.ttf
  ogre/src/media/fonts/roboto/Roboto-BlackItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Bold.ttf
  ogre/src/media/fonts/roboto/Roboto-BoldItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Italic.ttf
  ogre/src/media/fonts/roboto/Roboto-Light.ttf
  ogre/src/media/fonts/roboto/Roboto-LightItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Medium.ttf
  ogre/src/media/fonts/roboto/Roboto-MediumItalic.ttf
  ogre/src/media/fonts/roboto/Roboto-Regular.ttf
  ogre/src/media/fonts/roboto/Roboto-Thin.ttf
  ogre/src/media/fonts/roboto/Roboto-ThinItalic.ttf
  test/common_test/Text_TEST.cc
Labels: 🏛️ ionic

#1044 Update badges to point to gz-rendering9
  README.md
Labels: 🏛️ ionic

#1046 Prepare for gz-rendeirng9.0.0~pre2 release
  CMakeLists.txt
Labels: 🏛️ ionic
