Repository gazebosim/gz-rendering, pull requests merged in 2024-06, with the labels that each got.

#1008 Fix crash when visualizing Lidars with points
  ogre2/src/media/materials/programs/GLSL/point_vs.glsl
Labels: 🏯 fortress

#1003 Adding cone primitives.
  include/gz/rendering/Marker.hh
  include/gz/rendering/ParticleEmitter.hh
  ogre/src/OgreMarker.cc
  ogre2/src/Ogre2Marker.cc
Labels: 🏛️ ionic

#1009 Fixes deleter passed to the std::shared_ptr<void>
  src/ShaderParam.cc
Labels: 🎵 harmonic

#1001 Add Cone as a primitive parametric shape.
  include/gz/rendering/Marker.hh
  include/gz/rendering/ParticleEmitter.hh
  ogre/src/OgreMarker.cc
  ogre2/src/Ogre2Marker.cc
Labels: 🎵 harmonic

#1011 Prepare for 8.2.0
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#1013 Use single cubemap camera in lidar
  ogre2/src/Ogre2GpuRays.cc
Labels: 🎵 harmonic

#1012 Fix lidar 1st pass texture resolution calculation for FOV < 90 degrees
  ogre2/src/Ogre2GpuRays.cc
  test/integration/gpu_rays.cc
Labels: 🎵 harmonic
