Repository gazebosim/gz-rendering, pull requests merged in 2024-01, with the labels that each got.

#949 Remove todo in gpu ray test
  test/integration/gpu_rays.cc
Labels: 🎵 harmonic

#951 Merge 7 -> 8
  examples/actor_animation/Main.cc
  examples/boundingbox_camera/Main.cc
  examples/camera_tracking/Main.cc
  examples/custom_scene_viewer/ManualSceneDemo.cc
  examples/custom_shaders_uniforms/Main.cc
  examples/depth_camera/Main.cc
  examples/heightmap/Main.cc
  examples/lidar_visual/Main.cc
  examples/mesh_viewer/Main.cc
  examples/mouse_picking/Main.cc
  examples/ogre2_demo/Main.cc
  examples/particles_demo/Main.cc
  examples/projector/Main.cc
  examples/render_pass/Main.cc
  examples/segmentation_camera/Main.cc
  examples/simple_demo/Main.cc
  examples/simple_demo_qml/ThreadRenderer.cpp
  examples/thermal_camera/Main.cc
  examples/transform_control/Main.cc
  examples/view_control/Main.cc
  examples/visualization_demo/Main.cc
  examples/waves/Main.cc
  examples/wide_angle_camera/Main.cc
  include/gz/rendering/Utils.hh
  ogre2/src/terrain/Terra/CMakeLists.txt
  src/Utils.cc
Labels: 🎵 harmonic

#952 Prepare for 3.7.2 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#953 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#954 Merge ign-rendering3 ➡️ ign-rendering6
  Changelog.md
Labels: 🏯 fortress

#956 Backport ogre2 lidar performance improvement changes
  ogre2/src/Ogre2GpuRays.cc
Labels: 🏯 fortress

#957 Merge ign-rendering6 ➡️ gz-rendering7
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  include/gz/rendering/base/BaseGizmoVisual.hh
  ogre2/src/media/materials/scripts/GpuRays.compositor
Labels: 🌱 garden

#958 Prepare release 6.6.3
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#960 Update 6.6.3 changelog
  Changelog.md
Labels: 🏯 fortress

#961 Fix repeatedly loading engine when calling sceneFromFirstEngine
  src/RenderEngineManager.cc
Labels: 🎵 harmonic

#964 port: 8 to 9
  README.md
  examples/actor_animation/Main.cc
  examples/boundingbox_camera/Main.cc
  examples/camera_tracking/Main.cc
  examples/custom_scene_viewer/ManualSceneDemo.cc
  examples/custom_shaders_uniforms/Main.cc
  examples/depth_camera/Main.cc
  examples/heightmap/Main.cc
  examples/lidar_visual/Main.cc
  examples/mesh_viewer/Main.cc
  examples/mouse_picking/Main.cc
  examples/ogre2_demo/Main.cc
  examples/particles_demo/Main.cc
  examples/projector/Main.cc
  examples/render_pass/Main.cc
  examples/segmentation_camera/Main.cc
  examples/simple_demo/Main.cc
  examples/simple_demo_qml/ThreadRenderer.cpp
  examples/thermal_camera/Main.cc
  examples/transform_control/Main.cc
  examples/view_control/Main.cc
  examples/visualization_demo/Main.cc
  examples/waves/Main.cc
  examples/wide_angle_camera/Main.cc
  include/gz/rendering/Utils.hh
  ogre2/src/Ogre2Projector.cc
  ogre2/src/media/materials/scripts/GpuRays.compositor
  ogre2/src/terrain/Terra/CMakeLists.txt
  src/RenderEngineManager.cc
  src/Utils.cc
  test/integration/gpu_rays.cc
Labels: 🏛️ ionic

#966 Merge 7 ➡️ 8
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/triage.yml
  Changelog.md
  include/gz/rendering/base/BaseGizmoVisual.hh
Labels: 🎵 harmonic

#965 Optimize Ogre2DepthCamera performance by skipping color target passes when there are no connections
  ogre2/src/Ogre2DepthCamera.cc
Labels: 🎵 harmonic
