Repository gazebosim/gz-rendering, pull requests merged in 2024-05, with the labels that each got.

#981 Add package.xml
  .github/workflows/package_xml.yml
  package.xml
Labels: 🎵 harmonic

#1005 Fix gz-cmake declaration on package.xml (fix windows CI)
  package.xml
Labels: 🎵 harmonic

#996 Parse correctly OGRE2_RESOURCE_PATH on Windows
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🌱 garden

#1006 Merge 8 -> main
  .github/workflows/package_xml.yml
  CMakeLists.txt
  Changelog.md
  doc/CMakeLists.txt
  examples/actor_animation/Main.cc
  examples/boundingbox_camera/Main.cc
  examples/depth_camera/Main.cc
  examples/global_illumination/Main.cc
  examples/lux_core_engine/Main.cc
  examples/mesh_viewer/Main.cc
  examples/ogre2_demo/Main.cc
  examples/particles_demo/Main.cc
  examples/segmentation_camera/Main.cc
  examples/thermal_camera/Main.cc
  examples/waves/Main.cc
  include/gz/rendering/Camera.hh
  include/gz/rendering/Object.hh
  include/gz/rendering/Visual.hh
  include/gz/rendering/base/BaseRenderTarget.hh
  ogre/src/CMakeLists.txt
  ogre/src/OgreMeshFactory.cc
  ogre/src/media/fonts/CMakeLists.txt
  ogre/src/media/materials/programs/CMakeLists.txt
  ogre/src/media/materials/scripts/CMakeLists.txt
  ogre/src/media/materials/textures/CMakeLists.txt
  ogre/src/media/rtshaderlib150/CMakeLists.txt
  ogre2/src/CMakeLists.txt
  ogre2/src/Ogre2BoundingBoxCamera.cc
  ogre2/src/Ogre2DepthCamera.cc
  ogre2/src/Ogre2Marker.cc
  ogre2/src/Ogre2MeshFactory.cc
  ogre2/src/Ogre2RenderEngine.cc
  ogre2/src/Ogre2SegmentationCamera.cc
  ogre2/src/Ogre2ThermalCamera.cc
  optix/src/CMakeLists.txt
  package.xml
  src/base/BaseScene.cc
  src/base/media/materials/textures/CMakeLists.txt
  test/common_test/MeshDescriptor_TEST.cc
  test/common_test/Mesh_TEST.cc
  test/integration/depth_camera.cc
  test/integration/waves.cc
Labels: 🏛️ ionic
