Repository gazebosim/gz-rendering, pull requests merged in 2024-11, with the labels that each got.

#1082 Check valid camera near far clip distances
  include/gz/rendering/base/BaseCamera.hh
  ogre/src/OgreCamera.cc
  ogre2/src/Ogre2Camera.cc
  test/common_test/Camera_TEST.cc
Labels: 🏛️ ionic

#1083 Do not create wirebox with empty AABB (ogre)
  ogre/src/OgreWireBox.cc
Labels: ogre1.x, 🏛️ ionic, 🪵 jetty

#1085 Prepare for 8.2.1 release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🎵 harmonic

#1084 Prepare for 7.5.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden
