Repository gazebosim/gz-rendering, pull requests merged in 2024-04, with the labels that each got.

#984 Use relative install paths for plugin shared libraries and media files
  doc/CMakeLists.txt
  ogre/src/CMakeLists.txt
  ogre/src/media/fonts/CMakeLists.txt
  ogre/src/media/materials/programs/CMakeLists.txt
  ogre/src/media/materials/scripts/CMakeLists.txt
  ogre/src/media/materials/textures/CMakeLists.txt
  ogre/src/media/rtshaderlib150/CMakeLists.txt
  ogre2/src/CMakeLists.txt
  optix/src/CMakeLists.txt
  src/base/media/materials/textures/CMakeLists.txt
Labels: 🎵 harmonic

#985 Prepare for 8.1.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🎵 harmonic

#983 Work around conda-forge's CDT version of GL
  ogre/src/OgreRenderEngine.cc
Labels: 🏛️ ionic

#986 Fix compilation on simple_demo_qml on Windows
  examples/simple_demo_qml/GzRenderer.cc
Labels: 🏛️ ionic

#989 Fix unused variable warnings
  include/gz/rendering/base/BaseGlobalIlluminationVct.hh
Labels: 🏛️ ionic

#987 Fix simple_demo on Windows
  examples/simple_demo/CMakeLists.txt
  examples/simple_demo/GlutWindow.cc
  examples/simple_demo/Main.cc
Labels: 🏛️ ionic

#990 Find python directly instead of using GzPython
  test/gz_rendering_test.cmake
Labels: 🏛️ ionic

#992 Ogre2RenderEngine: on Windows if useCurrentGLContext is specified, set the externalWindowHandle ogre-next option
  ogre2/src/Ogre2RenderEngine.cc
Labels: 🎵 harmonic

#994 Fixed integer underflow in OgreDistortionPass
  ogre/src/OgreDistortionPass.cc
Labels: 🏯 fortress
